#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Aug 17 14:07:51 EDT 2025
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim hilbert_tb_func_synth -key {Post-Synthesis:sim_1:Functional:hilbert_tb} -tclbatch hilbert_tb.tcl -log simulate.log"
xsim hilbert_tb_func_synth -key {Post-Synthesis:sim_1:Functional:hilbert_tb} -tclbatch hilbert_tb.tcl -log simulate.log

