% Auto generated function to simulate the generated HDL code using cosimulation
% 
% Generated by MATLAB 25.2 and HDL Coder 25.2

function [ref_dataOut,ref_validOut] = hilbert_fir_filter_1027_cosim(dataIn,validIn,resetIn)

coder.extrinsic('hilbert_fir_filter_1027_sysobj_cosim');
coder.extrinsic('hdlverifier.assert');
coder.extrinsic('hdlverifier.Delay');
coder.extrinsic('step');

% Declare persistent variables
persistent initialized;

% Initialize persistent variables
if isempty(initialized)
   initialized = true;
end

% Call the original MATLAB function to get reference signal
[ref_dataOut,ref_validOut] = hilbert_fir_filter_1027(dataIn,validIn,resetIn);

% Run cosimulation
[dataOut,validOut] = hilbert_fir_filter_1027_sysobj_cosim(dataIn,validIn,resetIn);

% Convert output signals
validOut = logical(validOut);


% Verify the cosimulation output
hdlverifier.assert(dataOut,ref_dataOut,'dataOut');
hdlverifier.assert(validOut,ref_validOut,'validOut');

