% Auto generated function to compile/launch Vivado Simulator simulator
% 
% Generated by MATLAB 25.2 and HDL Coder 25.2

function launch_hilbert_fir_filter_cosim
[s,r] = system('vivado -mode batch -source C:\Users\Aweso\MATLAB\codegen\hilbert_fir_filter\cosim\launch_hilbert_fir_filter_cosim.tcl','-echo');
if s
   error('Failed to create Vivado HDL design DLL using script C:\Users\Aweso\MATLAB\codegen\hilbert_fir_filter\cosim\launch_hilbert_fir_filter_cosim.tcl.');
end


