% Function localRecompile_hilbert_fir_filter_1027_cosim recreates a MEX-function hilbert_fir_filter_1027_cosim_mex from MATLAB function hilbert_fir_filter_1027_cosim
% Generated by MATLAB 25.2 and HDL Coder 25.2
function localRecompile_hilbert_fir_filter_1027_cosim

load('C:\Users\Aweso\Verilog\Aquapack\bartlett\sim\bartlett_datapath\codegen\hilbert_fir_filter_1027\cosim\localCodegenArgs_hilbert_fir_filter_1027_cosim');

codegen -args exInputs -o 'C:\Users\Aweso\Verilog\Aquapack\bartlett\sim\bartlett_datapath\codegen\hilbert_fir_filter_1027\cosim\hilbert_fir_filter_1027_cosim_mex' hilbert_fir_filter_1027_cosim;

