% Function localRecompile_hilbert_fir_filter_cosim recreates a MEX-function hilbert_fir_filter_cosim_mex from MATLAB function hilbert_fir_filter_cosim
% Generated by MATLAB 25.2 and HDL Coder 25.2
function localRecompile_hilbert_fir_filter_cosim

load('C:\Users\Aweso\MATLAB\codegen\hilbert_fir_filter\cosim\localCodegenArgs_hilbert_fir_filter_cosim');

codegen -args exInputs -o 'C:\Users\Aweso\MATLAB\codegen\hilbert_fir_filter\cosim\hilbert_fir_filter_cosim_mex' hilbert_fir_filter_cosim;

