% Auto generated function to execute the generated cosimulation test bench
% 
% Generated by MATLAB 25.2 and HDL Coder 25.2

function run_hilbert_fir_filter_1027_cosim

% Launch HDL simulator
disp('### Launching Vivado Simulator for cosimulation ');
launch_hilbert_fir_filter_1027_cosim;

% Clear persistent variables before simulation
l_clearPersistentVariable;

% Clear persistent variables after simulation
onCleanupObj = onCleanup(@() l_clearPersistentVariable);

% Add current working directory to search path
savedPathVar = addpath(pwd);
restorePathObj = onCleanup(@() path(savedPathVar));

% Run generated test bench
disp('### Simulating generated test bench ');
% Exercise the compiled version of hilbert_fir_filter_1027_cosim in the generated test bench.
% To debug the test bench with the original function "hilbert_fir_filter_1027_cosim",
% replace the next line with "hilbert_fir_filter_1027_tb_cosim"
coder.runTest('localRunTest_hilbert_fir_filter_1027','hilbert_fir_filter_1027_cosim');
% To recompile MATLAB function "hilbert_fir_filter_1027_cosim",
% run the re-compilation function "localRecompile_hilbert_fir_filter_1027_cosim".
disp('### Finished Simulation');

end

function l_clearPersistentVariable
% Clear reference DUT function
clear hilbert_fir_filter_1027;

% Clear cosimulation System object wrapper function
clear hilbert_fir_filter_1027_sysobj_cosim;

% Clear cosimulation function
clear hilbert_fir_filter_1027_cosim;

% Clear generated MEX function
clear hilbert_fir_filter_1027_cosim_mex

end

