# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bigpi/AMD/Vivado/2022.2/Projects/hilbert_final/hilbert_final.srcs/sources_1/ip/xfft_256pt_32bit/xfft_256pt_32bit.xci
# IP: The module: 'xfft_256pt_32bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bigpi/AMD/Vivado/2022.2/Projects/hilbert_final/hilbert_final.gen/sources_1/ip/xfft_256pt_32bit/xfft_256pt_32bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_256pt_32bit'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/bigpi/AMD/Vivado/2022.2/Projects/hilbert_final/hilbert_final.srcs/sources_1/ip/xfft_256pt_32bit/xfft_256pt_32bit.xci
# IP: The module: 'xfft_256pt_32bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bigpi/AMD/Vivado/2022.2/Projects/hilbert_final/hilbert_final.gen/sources_1/ip/xfft_256pt_32bit/xfft_256pt_32bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_256pt_32bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
