# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Cmod-A7-Master.xdc

# IP: ip/cmpy_rxx/cmpy_rxx.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_rxx || ORIG_REF_NAME==cmpy_rxx} -quiet] -quiet
