# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.cache/wt [current_project]
set_property parent.project_path C:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog C:/Users/Aweso/Verilog/Aquapack/bartlett/src/Bartlett/constants.vh
read_verilog -library xil_defaultlib {
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/BIT_COUNTER.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/SPI/CDC_DRIVER.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/GENERAL_COUNTER.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/RING_BUFFER.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/UART/RX_SHIFT_REGISTER.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/SPI/SIPO.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/SPI/SPI.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/SPI/SPI_CONTROLLER.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/SPI/SPI_DATAPATH.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/SPI_TRANSACTION_HANDLER.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/SPI/SPI_WRAPPER.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/UART/UART.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/UART/UART_RX.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/UART/UART_RX_CONTROLLER.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/UART/UART_RX_DATAPATH.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/UART_TRANSACTION_HANDLER.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/UART/UART_TX.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/UART/UART_TX_CONTROLLER.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/UART/UART_TX_DATAPATH.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/Bartlett/time_domain/p_theta/accumulator.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/Bartlett/bartlett.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/Bartlett/bartlett_config_controller.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/Bartlett/time_domain/bartlett_time_domain.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/clk_div.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/command_reader.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/Bartlett/time_domain/common.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/Bartlett/fft_max.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/Bartlett/time_domain/max.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/Bartlett/time_domain/p_theta/p_theta.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/Bartlett/time_domain/rxx/rxx.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/Bartlett/time_domain/p_theta/s_theta.v
  C:/Users/Aweso/Verilog/Aquapack/bartlett/src/top.v
}
read_ip -quiet C:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.srcs/sources_1/ip/cmpy_rxx/cmpy_rxx.xci
set_property used_in_implementation false [get_files -all c:/Users/Aweso/Verilog/Aquapack/bartlett/bartlett.gen/sources_1/ip/cmpy_rxx/cmpy_rxx_ooc.xdc]

read_ip -quiet C:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.srcs/sources_1/ip/RING_BUFFER_RAM/RING_BUFFER_RAM.xci
set_property used_in_implementation false [get_files -all c:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.gen/sources_1/ip/RING_BUFFER_RAM/RING_BUFFER_RAM_ooc.xdc]

read_ip -quiet C:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.srcs/sources_1/ip/xfft_0/xfft_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Aweso/Verilog/Aquapack/bartlett/bartlett.gen/sources_1/ip/xfft_0_1/xfft_0_ooc.xdc]

read_ip -quiet C:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.srcs/sources_1/ip/cmpy_1/cmpy_1.xci
set_property used_in_implementation false [get_files -all c:/Users/Aweso/Verilog/Aquapack/bartlett/bartlett.gen/sources_1/ip/cmpy_1/cmpy_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.srcs/constrs_1/imports/Downloads/Cmod-A7-Master.xdc
set_property used_in_implementation false [get_files C:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.srcs/constrs_1/imports/Downloads/Cmod-A7-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/Aweso/Verilog/Aquapack/bartlett/SW9A-AcousticsFPGA.srcs/utils_1/imports/synth_1/top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
