// -------------------------------------------------------------
// 
// File Name: C:\Users\Aweso\hdlsrc\aquapack_9_5\aquapack_9_5\Cosine_HDL_Optimized_block1.v
// Created: 2026-09-14 17:02:34
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Cosine_HDL_Optimized_block1
// Source Path: aquapack_9_5/Parallel Beamformer/Distance Finder2/Cosine HDL Optimized
// Hierarchy Level: 2
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Cosine_HDL_Optimized_block1
          (clk,
           reset,
           enb,
           u,
           x,
           y);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] u;  // sfix16_En12
  output  signed [16:0] x;  // sfix17_En15
  output  signed [16:0] y;  // sfix17_En15


  wire [10:0] insig_out1;  // ufix11_En11
  wire [16:0] Point50_out1;  // ufix17_En17
  wire [16:0] LTEp501_cast;  // ufix17_En17
  wire LTEp50_out1;
  reg  RAMDelayBalance_out1;
  wire pow2switch_out1;
  wire signed [17:0] Amp50_sub_cast;  // sfix18_En17
  wire signed [17:0] Amp50_sub_cast_1;  // sfix18_En17
  wire signed [17:0] Amp50_out1;  // sfix18_En17
  wire signed [17:0] insig_out1_dtc;  // sfix18_En17
  wire signed [17:0] QuadHandle1_out1;  // sfix18_En17
  wire [16:0] Point25_out1;  // ufix17_En17
  wire signed [17:0] LTEp251_cast;  // sfix18_En17
  wire LTEp25_out1;
  wire signed [18:0] p50mA_sub_cast;  // sfix19_En17
  wire signed [18:0] p50mA_sub_cast_1;  // sfix19_En17
  wire signed [18:0] p50mA_out1;  // sfix19_En17
  wire [10:0] p50mA_out1_dtc;  // ufix11_En11
  wire [10:0] QuadHandle1_out1_dtc;  // ufix11_En11
  wire [10:0] QuadHandle2_out1;  // ufix11_En11
  wire [10:0] CastU16En2_out1;  // ufix11
  wire [11:0] CastU16En4_out1;  // ufix12
  wire [10:0] CastU16En3_out1;  // ufix11
  wire [10:0] UpperLimit_out;  // ufix11
  wire Sat_UpperRelOp_out;
  wire [10:0] LowerLimit_out;  // ufix11
  wire Sat_LowerRelOp_out;
  wire [10:0] Sat_LowerSwitch_out;  // ufix11
  wire [10:0] Saturation_out1;  // ufix11
  wire [10:0] Switch_out1;  // ufix11
  wire [8:0] prelookup_idx;  // ufix9
  wire signed [16:0] Look_Up_Table_1 [0:511];  // sfix17_En15 [512]
  wire signed [16:0] Look_Up_Table_out1;  // sfix17_En15
  reg signed [16:0] Unit_Delay_out1;  // sfix17_En15
  wire signed [17:0] Negate1_cast;  // sfix18_En15
  wire signed [17:0] Negate1_cast_1;  // sfix18_En15
  wire signed [16:0] Negate_out1;  // sfix17_En15
  wire signed [16:0] Sine;  // sfix17_En15
  wire [10:0] insig_out1_1;  // ufix11_En11
  wire [16:0] Point25_out1_1;  // ufix17_En17
  wire [16:0] LTEp25_cast;  // ufix17_En17
  wire LTEp25_out1_1;
  wire [16:0] Point75_out1;  // ufix17_En17
  wire [16:0] GTEp75_cast;  // ufix17_En17
  wire GTEp75_out1;
  wire alpha1st_or_4th_Quad_bool;
  wire [7:0] alpha1st_or_4th_Quad_out1;  // uint8
  reg [7:0] RAMDelayBalance_out1_1;  // uint8
  wire pow2switch_out1_1;
  wire [16:0] Point50_out1_1;  // ufix17_En17
  wire signed [17:0] p75mA_sub_cast;  // sfix18_En17
  wire signed [17:0] p75mA_sub_cast_1;  // sfix18_En17
  wire signed [17:0] p75mA_out1;  // sfix18_En17
  wire signed [17:0] Amp75_sub_cast;  // sfix18_En17
  wire signed [17:0] Amp75_sub_cast_1;  // sfix18_En17
  wire signed [17:0] Amp75_out1;  // sfix18_En17
  wire signed [17:0] Amp25_sub_cast;  // sfix18_En17
  wire signed [17:0] Amp25_sub_cast_1;  // sfix18_En17
  wire signed [17:0] Amp25_out1;  // sfix18_En17
  wire signed [17:0] p25mA_sub_cast;  // sfix18_En17
  wire signed [17:0] p25mA_sub_cast_1;  // sfix18_En17
  wire signed [17:0] p25mA_out1;  // sfix18_En17
  wire [16:0] LTEp50_cast;  // ufix17_En17
  wire LTEp50_out1_1;
  wire signed [17:0] QuadHandle1b_out1;  // sfix18_En17
  wire [10:0] QuadHandle1b_out1_dtc;  // ufix11_En11
  wire signed [17:0] QuadHandle1a_out1;  // sfix18_En17
  wire [10:0] QuadHandle1a_out1_dtc;  // ufix11_En11
  wire [10:0] QuadHandle2_out1_1;  // ufix11_En11
  wire [10:0] CastU16En1_out1;  // ufix11
  wire [11:0] CastU16En3_out1_1;  // ufix12
  wire [10:0] CastU16En2_out1_1;  // ufix11
  wire [10:0] UpperLimit_out_1;  // ufix11
  wire Sat_UpperRelOp_out_1;
  wire [10:0] LowerLimit_out_1;  // ufix11
  wire Sat_LowerRelOp_out_1;
  wire [10:0] Sat_LowerSwitch_out_1;  // ufix11
  wire [10:0] Saturation_out1_1;  // ufix11
  wire [10:0] Switch_out1_1;  // ufix11
  wire [8:0] prelookup_idx_1;  // ufix9
  wire signed [16:0] Look_Up_Table_3 [0:511];  // sfix17_En15 [512]
  wire signed [16:0] Look_Up_Table_out1_1;  // sfix17_En15
  reg signed [16:0] Unit_Delay_out1_1;  // sfix17_En15
  wire signed [17:0] Negate_cast;  // sfix18_En15
  wire signed [17:0] Negate_cast_1;  // sfix18_En15
  wire signed [16:0] Negate_out1_1;  // sfix17_En15
  wire signed [16:0] Cosine;  // sfix17_En15

  initial begin
    Unit_Delay_out1 = 17'sb00000000000000000;
    Unit_Delay_out1_1 = 17'sb00000000000000000;
  end
  // (C) 2016 Mathworks, Inc
  // (C) 2016 Mathworks, Inc


  assign insig_out1 = u[11:1];

  assign Point50_out1 = 17'b10000000000000000;

  assign LTEp501_cast = {insig_out1, 6'b000000};
  assign LTEp50_out1 = LTEp501_cast <= Point50_out1;

  always @(posedge clk)
    begin : RAMDelayBalance1_process
      if (reset == 1'b0) begin
        RAMDelayBalance_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          RAMDelayBalance_out1 <= LTEp50_out1;
        end
      end
    end

  assign pow2switch_out1 = 1'b1;

  assign Amp50_sub_cast = {1'b0, {insig_out1, 6'b000000}};
  assign Amp50_sub_cast_1 = {1'b0, Point50_out1};
  assign Amp50_out1 = Amp50_sub_cast - Amp50_sub_cast_1;

  assign insig_out1_dtc = {1'b0, {insig_out1, 6'b000000}};

  assign QuadHandle1_out1 = (LTEp50_out1 == 1'b0 ? Amp50_out1 :
              insig_out1_dtc);

  assign Point25_out1 = 17'b01000000000000000;

  assign LTEp251_cast = {1'b0, Point25_out1};
  assign LTEp25_out1 = QuadHandle1_out1 <= LTEp251_cast;

  assign p50mA_sub_cast = {2'b0, Point50_out1};
  assign p50mA_sub_cast_1 = {QuadHandle1_out1[17], QuadHandle1_out1};
  assign p50mA_out1 = p50mA_sub_cast - p50mA_sub_cast_1;

  assign p50mA_out1_dtc = p50mA_out1[16:6];

  assign QuadHandle1_out1_dtc = QuadHandle1_out1[16:6];

  assign QuadHandle2_out1 = (LTEp25_out1 == 1'b0 ? p50mA_out1_dtc :
              QuadHandle1_out1_dtc);

  assign CastU16En2_out1 = QuadHandle2_out1;

  assign CastU16En4_out1 = {1'b0, CastU16En2_out1};

  assign CastU16En3_out1 = (CastU16En4_out1[11] != 1'b0 ? 11'b11111111111 :
              CastU16En4_out1[10:0]);

  assign UpperLimit_out = 11'b00111111111;

  assign Sat_UpperRelOp_out = CastU16En3_out1 > UpperLimit_out;

  assign LowerLimit_out = 11'b00000000000;

  assign Sat_LowerRelOp_out = CastU16En3_out1 < LowerLimit_out;

  assign Sat_LowerSwitch_out = (Sat_LowerRelOp_out == 1'b0 ? CastU16En3_out1 :
              LowerLimit_out);

  assign Saturation_out1 = (Sat_UpperRelOp_out == 1'b0 ? Sat_LowerSwitch_out :
              UpperLimit_out);

  assign Switch_out1 = (pow2switch_out1 == 1'b0 ? CastU16En3_out1 :
              Saturation_out1);

  assign prelookup_idx = (Switch_out1 == 11'b00000000000 ? 9'b000000000 :
              (Switch_out1 >= 11'b00111111111 ? 9'b111111111 :
              Switch_out1[8:0]));

  assign Look_Up_Table_1[0] = 17'sb00000000000000000;
  assign Look_Up_Table_1[1] = 17'sb00000000001100101;
  assign Look_Up_Table_1[2] = 17'sb00000000011001001;
  assign Look_Up_Table_1[3] = 17'sb00000000100101110;
  assign Look_Up_Table_1[4] = 17'sb00000000110010011;
  assign Look_Up_Table_1[5] = 17'sb00000000111111000;
  assign Look_Up_Table_1[6] = 17'sb00000001001011100;
  assign Look_Up_Table_1[7] = 17'sb00000001011000001;
  assign Look_Up_Table_1[8] = 17'sb00000001100100110;
  assign Look_Up_Table_1[9] = 17'sb00000001110001010;
  assign Look_Up_Table_1[10] = 17'sb00000001111101111;
  assign Look_Up_Table_1[11] = 17'sb00000010001010100;
  assign Look_Up_Table_1[12] = 17'sb00000010010111000;
  assign Look_Up_Table_1[13] = 17'sb00000010100011101;
  assign Look_Up_Table_1[14] = 17'sb00000010110000010;
  assign Look_Up_Table_1[15] = 17'sb00000010111100110;
  assign Look_Up_Table_1[16] = 17'sb00000011001001011;
  assign Look_Up_Table_1[17] = 17'sb00000011010110000;
  assign Look_Up_Table_1[18] = 17'sb00000011100010100;
  assign Look_Up_Table_1[19] = 17'sb00000011101111001;
  assign Look_Up_Table_1[20] = 17'sb00000011111011101;
  assign Look_Up_Table_1[21] = 17'sb00000100001000010;
  assign Look_Up_Table_1[22] = 17'sb00000100010100110;
  assign Look_Up_Table_1[23] = 17'sb00000100100001011;
  assign Look_Up_Table_1[24] = 17'sb00000100101101111;
  assign Look_Up_Table_1[25] = 17'sb00000100111010100;
  assign Look_Up_Table_1[26] = 17'sb00000101000111000;
  assign Look_Up_Table_1[27] = 17'sb00000101010011101;
  assign Look_Up_Table_1[28] = 17'sb00000101100000001;
  assign Look_Up_Table_1[29] = 17'sb00000101101100101;
  assign Look_Up_Table_1[30] = 17'sb00000101111001010;
  assign Look_Up_Table_1[31] = 17'sb00000110000101110;
  assign Look_Up_Table_1[32] = 17'sb00000110010010010;
  assign Look_Up_Table_1[33] = 17'sb00000110011110110;
  assign Look_Up_Table_1[34] = 17'sb00000110101011011;
  assign Look_Up_Table_1[35] = 17'sb00000110110111111;
  assign Look_Up_Table_1[36] = 17'sb00000111000100011;
  assign Look_Up_Table_1[37] = 17'sb00000111010000111;
  assign Look_Up_Table_1[38] = 17'sb00000111011101011;
  assign Look_Up_Table_1[39] = 17'sb00000111101001111;
  assign Look_Up_Table_1[40] = 17'sb00000111110110011;
  assign Look_Up_Table_1[41] = 17'sb00001000000010111;
  assign Look_Up_Table_1[42] = 17'sb00001000001111011;
  assign Look_Up_Table_1[43] = 17'sb00001000011011111;
  assign Look_Up_Table_1[44] = 17'sb00001000101000011;
  assign Look_Up_Table_1[45] = 17'sb00001000110100110;
  assign Look_Up_Table_1[46] = 17'sb00001001000001010;
  assign Look_Up_Table_1[47] = 17'sb00001001001101110;
  assign Look_Up_Table_1[48] = 17'sb00001001011010001;
  assign Look_Up_Table_1[49] = 17'sb00001001100110101;
  assign Look_Up_Table_1[50] = 17'sb00001001110011001;
  assign Look_Up_Table_1[51] = 17'sb00001001111111100;
  assign Look_Up_Table_1[52] = 17'sb00001010001100000;
  assign Look_Up_Table_1[53] = 17'sb00001010011000011;
  assign Look_Up_Table_1[54] = 17'sb00001010100100110;
  assign Look_Up_Table_1[55] = 17'sb00001010110001010;
  assign Look_Up_Table_1[56] = 17'sb00001010111101101;
  assign Look_Up_Table_1[57] = 17'sb00001011001010000;
  assign Look_Up_Table_1[58] = 17'sb00001011010110011;
  assign Look_Up_Table_1[59] = 17'sb00001011100010110;
  assign Look_Up_Table_1[60] = 17'sb00001011101111001;
  assign Look_Up_Table_1[61] = 17'sb00001011111011100;
  assign Look_Up_Table_1[62] = 17'sb00001100000111111;
  assign Look_Up_Table_1[63] = 17'sb00001100010100010;
  assign Look_Up_Table_1[64] = 17'sb00001100100000101;
  assign Look_Up_Table_1[65] = 17'sb00001100101101000;
  assign Look_Up_Table_1[66] = 17'sb00001100111001011;
  assign Look_Up_Table_1[67] = 17'sb00001101000101101;
  assign Look_Up_Table_1[68] = 17'sb00001101010010000;
  assign Look_Up_Table_1[69] = 17'sb00001101011110010;
  assign Look_Up_Table_1[70] = 17'sb00001101101010101;
  assign Look_Up_Table_1[71] = 17'sb00001101110110111;
  assign Look_Up_Table_1[72] = 17'sb00001110000011001;
  assign Look_Up_Table_1[73] = 17'sb00001110001111100;
  assign Look_Up_Table_1[74] = 17'sb00001110011011110;
  assign Look_Up_Table_1[75] = 17'sb00001110101000000;
  assign Look_Up_Table_1[76] = 17'sb00001110110100010;
  assign Look_Up_Table_1[77] = 17'sb00001111000000100;
  assign Look_Up_Table_1[78] = 17'sb00001111001100110;
  assign Look_Up_Table_1[79] = 17'sb00001111011001000;
  assign Look_Up_Table_1[80] = 17'sb00001111100101001;
  assign Look_Up_Table_1[81] = 17'sb00001111110001011;
  assign Look_Up_Table_1[82] = 17'sb00001111111101100;
  assign Look_Up_Table_1[83] = 17'sb00010000001001110;
  assign Look_Up_Table_1[84] = 17'sb00010000010101111;
  assign Look_Up_Table_1[85] = 17'sb00010000100010001;
  assign Look_Up_Table_1[86] = 17'sb00010000101110010;
  assign Look_Up_Table_1[87] = 17'sb00010000111010011;
  assign Look_Up_Table_1[88] = 17'sb00010001000110100;
  assign Look_Up_Table_1[89] = 17'sb00010001010010101;
  assign Look_Up_Table_1[90] = 17'sb00010001011110110;
  assign Look_Up_Table_1[91] = 17'sb00010001101010111;
  assign Look_Up_Table_1[92] = 17'sb00010001110111000;
  assign Look_Up_Table_1[93] = 17'sb00010010000011001;
  assign Look_Up_Table_1[94] = 17'sb00010010001111001;
  assign Look_Up_Table_1[95] = 17'sb00010010011011010;
  assign Look_Up_Table_1[96] = 17'sb00010010100111010;
  assign Look_Up_Table_1[97] = 17'sb00010010110011010;
  assign Look_Up_Table_1[98] = 17'sb00010010111111011;
  assign Look_Up_Table_1[99] = 17'sb00010011001011011;
  assign Look_Up_Table_1[100] = 17'sb00010011010111011;
  assign Look_Up_Table_1[101] = 17'sb00010011100011011;
  assign Look_Up_Table_1[102] = 17'sb00010011101111011;
  assign Look_Up_Table_1[103] = 17'sb00010011111011010;
  assign Look_Up_Table_1[104] = 17'sb00010100000111010;
  assign Look_Up_Table_1[105] = 17'sb00010100010011010;
  assign Look_Up_Table_1[106] = 17'sb00010100011111001;
  assign Look_Up_Table_1[107] = 17'sb00010100101011001;
  assign Look_Up_Table_1[108] = 17'sb00010100110111000;
  assign Look_Up_Table_1[109] = 17'sb00010101000010111;
  assign Look_Up_Table_1[110] = 17'sb00010101001110110;
  assign Look_Up_Table_1[111] = 17'sb00010101011010101;
  assign Look_Up_Table_1[112] = 17'sb00010101100110100;
  assign Look_Up_Table_1[113] = 17'sb00010101110010011;
  assign Look_Up_Table_1[114] = 17'sb00010101111110001;
  assign Look_Up_Table_1[115] = 17'sb00010110001010000;
  assign Look_Up_Table_1[116] = 17'sb00010110010101110;
  assign Look_Up_Table_1[117] = 17'sb00010110100001101;
  assign Look_Up_Table_1[118] = 17'sb00010110101101011;
  assign Look_Up_Table_1[119] = 17'sb00010110111001001;
  assign Look_Up_Table_1[120] = 17'sb00010111000100111;
  assign Look_Up_Table_1[121] = 17'sb00010111010000101;
  assign Look_Up_Table_1[122] = 17'sb00010111011100011;
  assign Look_Up_Table_1[123] = 17'sb00010111101000000;
  assign Look_Up_Table_1[124] = 17'sb00010111110011110;
  assign Look_Up_Table_1[125] = 17'sb00010111111111011;
  assign Look_Up_Table_1[126] = 17'sb00011000001011001;
  assign Look_Up_Table_1[127] = 17'sb00011000010110110;
  assign Look_Up_Table_1[128] = 17'sb00011000100010011;
  assign Look_Up_Table_1[129] = 17'sb00011000101110000;
  assign Look_Up_Table_1[130] = 17'sb00011000111001101;
  assign Look_Up_Table_1[131] = 17'sb00011001000101010;
  assign Look_Up_Table_1[132] = 17'sb00011001010000110;
  assign Look_Up_Table_1[133] = 17'sb00011001011100011;
  assign Look_Up_Table_1[134] = 17'sb00011001100111111;
  assign Look_Up_Table_1[135] = 17'sb00011001110011011;
  assign Look_Up_Table_1[136] = 17'sb00011001111110111;
  assign Look_Up_Table_1[137] = 17'sb00011010001010011;
  assign Look_Up_Table_1[138] = 17'sb00011010010101111;
  assign Look_Up_Table_1[139] = 17'sb00011010100001011;
  assign Look_Up_Table_1[140] = 17'sb00011010101100111;
  assign Look_Up_Table_1[141] = 17'sb00011010111000010;
  assign Look_Up_Table_1[142] = 17'sb00011011000011101;
  assign Look_Up_Table_1[143] = 17'sb00011011001111001;
  assign Look_Up_Table_1[144] = 17'sb00011011011010100;
  assign Look_Up_Table_1[145] = 17'sb00011011100101111;
  assign Look_Up_Table_1[146] = 17'sb00011011110001010;
  assign Look_Up_Table_1[147] = 17'sb00011011111100100;
  assign Look_Up_Table_1[148] = 17'sb00011100000111111;
  assign Look_Up_Table_1[149] = 17'sb00011100010011001;
  assign Look_Up_Table_1[150] = 17'sb00011100011110011;
  assign Look_Up_Table_1[151] = 17'sb00011100101001110;
  assign Look_Up_Table_1[152] = 17'sb00011100110101000;
  assign Look_Up_Table_1[153] = 17'sb00011101000000001;
  assign Look_Up_Table_1[154] = 17'sb00011101001011011;
  assign Look_Up_Table_1[155] = 17'sb00011101010110101;
  assign Look_Up_Table_1[156] = 17'sb00011101100001110;
  assign Look_Up_Table_1[157] = 17'sb00011101101100111;
  assign Look_Up_Table_1[158] = 17'sb00011101111000001;
  assign Look_Up_Table_1[159] = 17'sb00011110000011010;
  assign Look_Up_Table_1[160] = 17'sb00011110001110010;
  assign Look_Up_Table_1[161] = 17'sb00011110011001011;
  assign Look_Up_Table_1[162] = 17'sb00011110100100100;
  assign Look_Up_Table_1[163] = 17'sb00011110101111100;
  assign Look_Up_Table_1[164] = 17'sb00011110111010100;
  assign Look_Up_Table_1[165] = 17'sb00011111000101101;
  assign Look_Up_Table_1[166] = 17'sb00011111010000101;
  assign Look_Up_Table_1[167] = 17'sb00011111011011100;
  assign Look_Up_Table_1[168] = 17'sb00011111100110100;
  assign Look_Up_Table_1[169] = 17'sb00011111110001100;
  assign Look_Up_Table_1[170] = 17'sb00011111111100011;
  assign Look_Up_Table_1[171] = 17'sb00100000000111010;
  assign Look_Up_Table_1[172] = 17'sb00100000010010001;
  assign Look_Up_Table_1[173] = 17'sb00100000011101000;
  assign Look_Up_Table_1[174] = 17'sb00100000100111111;
  assign Look_Up_Table_1[175] = 17'sb00100000110010101;
  assign Look_Up_Table_1[176] = 17'sb00100000111101100;
  assign Look_Up_Table_1[177] = 17'sb00100001001000010;
  assign Look_Up_Table_1[178] = 17'sb00100001010011000;
  assign Look_Up_Table_1[179] = 17'sb00100001011101110;
  assign Look_Up_Table_1[180] = 17'sb00100001101000100;
  assign Look_Up_Table_1[181] = 17'sb00100001110011010;
  assign Look_Up_Table_1[182] = 17'sb00100001111101111;
  assign Look_Up_Table_1[183] = 17'sb00100010001000100;
  assign Look_Up_Table_1[184] = 17'sb00100010010011001;
  assign Look_Up_Table_1[185] = 17'sb00100010011101110;
  assign Look_Up_Table_1[186] = 17'sb00100010101000011;
  assign Look_Up_Table_1[187] = 17'sb00100010110011000;
  assign Look_Up_Table_1[188] = 17'sb00100010111101100;
  assign Look_Up_Table_1[189] = 17'sb00100011001000000;
  assign Look_Up_Table_1[190] = 17'sb00100011010010101;
  assign Look_Up_Table_1[191] = 17'sb00100011011101001;
  assign Look_Up_Table_1[192] = 17'sb00100011100111100;
  assign Look_Up_Table_1[193] = 17'sb00100011110010000;
  assign Look_Up_Table_1[194] = 17'sb00100011111100011;
  assign Look_Up_Table_1[195] = 17'sb00100100000110111;
  assign Look_Up_Table_1[196] = 17'sb00100100010001010;
  assign Look_Up_Table_1[197] = 17'sb00100100011011101;
  assign Look_Up_Table_1[198] = 17'sb00100100100101111;
  assign Look_Up_Table_1[199] = 17'sb00100100110000010;
  assign Look_Up_Table_1[200] = 17'sb00100100111010100;
  assign Look_Up_Table_1[201] = 17'sb00100101000100110;
  assign Look_Up_Table_1[202] = 17'sb00100101001111000;
  assign Look_Up_Table_1[203] = 17'sb00100101011001010;
  assign Look_Up_Table_1[204] = 17'sb00100101100011100;
  assign Look_Up_Table_1[205] = 17'sb00100101101101101;
  assign Look_Up_Table_1[206] = 17'sb00100101110111111;
  assign Look_Up_Table_1[207] = 17'sb00100110000010000;
  assign Look_Up_Table_1[208] = 17'sb00100110001100001;
  assign Look_Up_Table_1[209] = 17'sb00100110010110001;
  assign Look_Up_Table_1[210] = 17'sb00100110100000010;
  assign Look_Up_Table_1[211] = 17'sb00100110101010010;
  assign Look_Up_Table_1[212] = 17'sb00100110110100011;
  assign Look_Up_Table_1[213] = 17'sb00100110111110011;
  assign Look_Up_Table_1[214] = 17'sb00100111001000010;
  assign Look_Up_Table_1[215] = 17'sb00100111010010010;
  assign Look_Up_Table_1[216] = 17'sb00100111011100001;
  assign Look_Up_Table_1[217] = 17'sb00100111100110001;
  assign Look_Up_Table_1[218] = 17'sb00100111110000000;
  assign Look_Up_Table_1[219] = 17'sb00100111111001111;
  assign Look_Up_Table_1[220] = 17'sb00101000000011101;
  assign Look_Up_Table_1[221] = 17'sb00101000001101100;
  assign Look_Up_Table_1[222] = 17'sb00101000010111010;
  assign Look_Up_Table_1[223] = 17'sb00101000100001000;
  assign Look_Up_Table_1[224] = 17'sb00101000101010110;
  assign Look_Up_Table_1[225] = 17'sb00101000110100100;
  assign Look_Up_Table_1[226] = 17'sb00101000111110001;
  assign Look_Up_Table_1[227] = 17'sb00101001000111110;
  assign Look_Up_Table_1[228] = 17'sb00101001010001011;
  assign Look_Up_Table_1[229] = 17'sb00101001011011000;
  assign Look_Up_Table_1[230] = 17'sb00101001100100101;
  assign Look_Up_Table_1[231] = 17'sb00101001101110001;
  assign Look_Up_Table_1[232] = 17'sb00101001110111110;
  assign Look_Up_Table_1[233] = 17'sb00101010000001010;
  assign Look_Up_Table_1[234] = 17'sb00101010001010110;
  assign Look_Up_Table_1[235] = 17'sb00101010010100001;
  assign Look_Up_Table_1[236] = 17'sb00101010011101101;
  assign Look_Up_Table_1[237] = 17'sb00101010100111000;
  assign Look_Up_Table_1[238] = 17'sb00101010110000011;
  assign Look_Up_Table_1[239] = 17'sb00101010111001110;
  assign Look_Up_Table_1[240] = 17'sb00101011000011001;
  assign Look_Up_Table_1[241] = 17'sb00101011001100011;
  assign Look_Up_Table_1[242] = 17'sb00101011010101101;
  assign Look_Up_Table_1[243] = 17'sb00101011011110111;
  assign Look_Up_Table_1[244] = 17'sb00101011101000001;
  assign Look_Up_Table_1[245] = 17'sb00101011110001011;
  assign Look_Up_Table_1[246] = 17'sb00101011111010100;
  assign Look_Up_Table_1[247] = 17'sb00101100000011101;
  assign Look_Up_Table_1[248] = 17'sb00101100001100110;
  assign Look_Up_Table_1[249] = 17'sb00101100010101111;
  assign Look_Up_Table_1[250] = 17'sb00101100011110111;
  assign Look_Up_Table_1[251] = 17'sb00101100101000000;
  assign Look_Up_Table_1[252] = 17'sb00101100110001000;
  assign Look_Up_Table_1[253] = 17'sb00101100111010000;
  assign Look_Up_Table_1[254] = 17'sb00101101000010111;
  assign Look_Up_Table_1[255] = 17'sb00101101001011111;
  assign Look_Up_Table_1[256] = 17'sb00101101010100110;
  assign Look_Up_Table_1[257] = 17'sb00101101011101101;
  assign Look_Up_Table_1[258] = 17'sb00101101100110100;
  assign Look_Up_Table_1[259] = 17'sb00101101101111010;
  assign Look_Up_Table_1[260] = 17'sb00101101111000001;
  assign Look_Up_Table_1[261] = 17'sb00101110000000111;
  assign Look_Up_Table_1[262] = 17'sb00101110001001101;
  assign Look_Up_Table_1[263] = 17'sb00101110010010010;
  assign Look_Up_Table_1[264] = 17'sb00101110011011000;
  assign Look_Up_Table_1[265] = 17'sb00101110100011101;
  assign Look_Up_Table_1[266] = 17'sb00101110101100010;
  assign Look_Up_Table_1[267] = 17'sb00101110110100111;
  assign Look_Up_Table_1[268] = 17'sb00101110111101011;
  assign Look_Up_Table_1[269] = 17'sb00101111000110000;
  assign Look_Up_Table_1[270] = 17'sb00101111001110100;
  assign Look_Up_Table_1[271] = 17'sb00101111010111000;
  assign Look_Up_Table_1[272] = 17'sb00101111011111011;
  assign Look_Up_Table_1[273] = 17'sb00101111100111111;
  assign Look_Up_Table_1[274] = 17'sb00101111110000010;
  assign Look_Up_Table_1[275] = 17'sb00101111111000101;
  assign Look_Up_Table_1[276] = 17'sb00110000000001000;
  assign Look_Up_Table_1[277] = 17'sb00110000001001010;
  assign Look_Up_Table_1[278] = 17'sb00110000010001100;
  assign Look_Up_Table_1[279] = 17'sb00110000011001110;
  assign Look_Up_Table_1[280] = 17'sb00110000100010000;
  assign Look_Up_Table_1[281] = 17'sb00110000101010010;
  assign Look_Up_Table_1[282] = 17'sb00110000110010011;
  assign Look_Up_Table_1[283] = 17'sb00110000111010100;
  assign Look_Up_Table_1[284] = 17'sb00110001000010101;
  assign Look_Up_Table_1[285] = 17'sb00110001001010110;
  assign Look_Up_Table_1[286] = 17'sb00110001010010110;
  assign Look_Up_Table_1[287] = 17'sb00110001011010110;
  assign Look_Up_Table_1[288] = 17'sb00110001100010110;
  assign Look_Up_Table_1[289] = 17'sb00110001101010110;
  assign Look_Up_Table_1[290] = 17'sb00110001110010101;
  assign Look_Up_Table_1[291] = 17'sb00110001111010100;
  assign Look_Up_Table_1[292] = 17'sb00110010000010011;
  assign Look_Up_Table_1[293] = 17'sb00110010001010010;
  assign Look_Up_Table_1[294] = 17'sb00110010010010000;
  assign Look_Up_Table_1[295] = 17'sb00110010011001110;
  assign Look_Up_Table_1[296] = 17'sb00110010100001100;
  assign Look_Up_Table_1[297] = 17'sb00110010101001010;
  assign Look_Up_Table_1[298] = 17'sb00110010110000111;
  assign Look_Up_Table_1[299] = 17'sb00110010111000101;
  assign Look_Up_Table_1[300] = 17'sb00110011000000010;
  assign Look_Up_Table_1[301] = 17'sb00110011000111110;
  assign Look_Up_Table_1[302] = 17'sb00110011001111011;
  assign Look_Up_Table_1[303] = 17'sb00110011010110111;
  assign Look_Up_Table_1[304] = 17'sb00110011011110011;
  assign Look_Up_Table_1[305] = 17'sb00110011100101111;
  assign Look_Up_Table_1[306] = 17'sb00110011101101010;
  assign Look_Up_Table_1[307] = 17'sb00110011110100110;
  assign Look_Up_Table_1[308] = 17'sb00110011111100001;
  assign Look_Up_Table_1[309] = 17'sb00110100000011011;
  assign Look_Up_Table_1[310] = 17'sb00110100001010110;
  assign Look_Up_Table_1[311] = 17'sb00110100010010000;
  assign Look_Up_Table_1[312] = 17'sb00110100011001010;
  assign Look_Up_Table_1[313] = 17'sb00110100100000100;
  assign Look_Up_Table_1[314] = 17'sb00110100100111101;
  assign Look_Up_Table_1[315] = 17'sb00110100101110110;
  assign Look_Up_Table_1[316] = 17'sb00110100110101111;
  assign Look_Up_Table_1[317] = 17'sb00110100111101000;
  assign Look_Up_Table_1[318] = 17'sb00110101000100000;
  assign Look_Up_Table_1[319] = 17'sb00110101001011001;
  assign Look_Up_Table_1[320] = 17'sb00110101010010001;
  assign Look_Up_Table_1[321] = 17'sb00110101011001000;
  assign Look_Up_Table_1[322] = 17'sb00110101100000000;
  assign Look_Up_Table_1[323] = 17'sb00110101100110111;
  assign Look_Up_Table_1[324] = 17'sb00110101101101110;
  assign Look_Up_Table_1[325] = 17'sb00110101110100100;
  assign Look_Up_Table_1[326] = 17'sb00110101111011011;
  assign Look_Up_Table_1[327] = 17'sb00110110000010001;
  assign Look_Up_Table_1[328] = 17'sb00110110001000111;
  assign Look_Up_Table_1[329] = 17'sb00110110001111100;
  assign Look_Up_Table_1[330] = 17'sb00110110010110010;
  assign Look_Up_Table_1[331] = 17'sb00110110011100111;
  assign Look_Up_Table_1[332] = 17'sb00110110100011011;
  assign Look_Up_Table_1[333] = 17'sb00110110101010000;
  assign Look_Up_Table_1[334] = 17'sb00110110110000100;
  assign Look_Up_Table_1[335] = 17'sb00110110110111000;
  assign Look_Up_Table_1[336] = 17'sb00110110111101100;
  assign Look_Up_Table_1[337] = 17'sb00110111000011111;
  assign Look_Up_Table_1[338] = 17'sb00110111001010011;
  assign Look_Up_Table_1[339] = 17'sb00110111010000110;
  assign Look_Up_Table_1[340] = 17'sb00110111010111000;
  assign Look_Up_Table_1[341] = 17'sb00110111011101011;
  assign Look_Up_Table_1[342] = 17'sb00110111100011101;
  assign Look_Up_Table_1[343] = 17'sb00110111101001111;
  assign Look_Up_Table_1[344] = 17'sb00110111110000000;
  assign Look_Up_Table_1[345] = 17'sb00110111110110010;
  assign Look_Up_Table_1[346] = 17'sb00110111111100011;
  assign Look_Up_Table_1[347] = 17'sb00111000000010011;
  assign Look_Up_Table_1[348] = 17'sb00111000001000100;
  assign Look_Up_Table_1[349] = 17'sb00111000001110100;
  assign Look_Up_Table_1[350] = 17'sb00111000010100100;
  assign Look_Up_Table_1[351] = 17'sb00111000011010100;
  assign Look_Up_Table_1[352] = 17'sb00111000100000011;
  assign Look_Up_Table_1[353] = 17'sb00111000100110011;
  assign Look_Up_Table_1[354] = 17'sb00111000101100001;
  assign Look_Up_Table_1[355] = 17'sb00111000110010000;
  assign Look_Up_Table_1[356] = 17'sb00111000110111110;
  assign Look_Up_Table_1[357] = 17'sb00111000111101100;
  assign Look_Up_Table_1[358] = 17'sb00111001000011010;
  assign Look_Up_Table_1[359] = 17'sb00111001001001000;
  assign Look_Up_Table_1[360] = 17'sb00111001001110101;
  assign Look_Up_Table_1[361] = 17'sb00111001010100010;
  assign Look_Up_Table_1[362] = 17'sb00111001011001111;
  assign Look_Up_Table_1[363] = 17'sb00111001011111011;
  assign Look_Up_Table_1[364] = 17'sb00111001100100111;
  assign Look_Up_Table_1[365] = 17'sb00111001101010011;
  assign Look_Up_Table_1[366] = 17'sb00111001101111111;
  assign Look_Up_Table_1[367] = 17'sb00111001110101010;
  assign Look_Up_Table_1[368] = 17'sb00111001111010101;
  assign Look_Up_Table_1[369] = 17'sb00111010000000000;
  assign Look_Up_Table_1[370] = 17'sb00111010000101010;
  assign Look_Up_Table_1[371] = 17'sb00111010001010100;
  assign Look_Up_Table_1[372] = 17'sb00111010001111110;
  assign Look_Up_Table_1[373] = 17'sb00111010010101000;
  assign Look_Up_Table_1[374] = 17'sb00111010011010001;
  assign Look_Up_Table_1[375] = 17'sb00111010011111010;
  assign Look_Up_Table_1[376] = 17'sb00111010100100011;
  assign Look_Up_Table_1[377] = 17'sb00111010101001011;
  assign Look_Up_Table_1[378] = 17'sb00111010101110011;
  assign Look_Up_Table_1[379] = 17'sb00111010110011011;
  assign Look_Up_Table_1[380] = 17'sb00111010111000011;
  assign Look_Up_Table_1[381] = 17'sb00111010111101010;
  assign Look_Up_Table_1[382] = 17'sb00111011000010001;
  assign Look_Up_Table_1[383] = 17'sb00111011000111000;
  assign Look_Up_Table_1[384] = 17'sb00111011001011111;
  assign Look_Up_Table_1[385] = 17'sb00111011010000101;
  assign Look_Up_Table_1[386] = 17'sb00111011010101011;
  assign Look_Up_Table_1[387] = 17'sb00111011011010000;
  assign Look_Up_Table_1[388] = 17'sb00111011011110110;
  assign Look_Up_Table_1[389] = 17'sb00111011100011011;
  assign Look_Up_Table_1[390] = 17'sb00111011100111111;
  assign Look_Up_Table_1[391] = 17'sb00111011101100100;
  assign Look_Up_Table_1[392] = 17'sb00111011110001000;
  assign Look_Up_Table_1[393] = 17'sb00111011110101100;
  assign Look_Up_Table_1[394] = 17'sb00111011111001111;
  assign Look_Up_Table_1[395] = 17'sb00111011111110011;
  assign Look_Up_Table_1[396] = 17'sb00111100000010110;
  assign Look_Up_Table_1[397] = 17'sb00111100000111001;
  assign Look_Up_Table_1[398] = 17'sb00111100001011011;
  assign Look_Up_Table_1[399] = 17'sb00111100001111101;
  assign Look_Up_Table_1[400] = 17'sb00111100010011111;
  assign Look_Up_Table_1[401] = 17'sb00111100011000000;
  assign Look_Up_Table_1[402] = 17'sb00111100011100010;
  assign Look_Up_Table_1[403] = 17'sb00111100100000011;
  assign Look_Up_Table_1[404] = 17'sb00111100100100011;
  assign Look_Up_Table_1[405] = 17'sb00111100101000100;
  assign Look_Up_Table_1[406] = 17'sb00111100101100100;
  assign Look_Up_Table_1[407] = 17'sb00111100110000100;
  assign Look_Up_Table_1[408] = 17'sb00111100110100011;
  assign Look_Up_Table_1[409] = 17'sb00111100111000010;
  assign Look_Up_Table_1[410] = 17'sb00111100111100001;
  assign Look_Up_Table_1[411] = 17'sb00111101000000000;
  assign Look_Up_Table_1[412] = 17'sb00111101000011110;
  assign Look_Up_Table_1[413] = 17'sb00111101000111100;
  assign Look_Up_Table_1[414] = 17'sb00111101001011010;
  assign Look_Up_Table_1[415] = 17'sb00111101001111000;
  assign Look_Up_Table_1[416] = 17'sb00111101010010101;
  assign Look_Up_Table_1[417] = 17'sb00111101010110010;
  assign Look_Up_Table_1[418] = 17'sb00111101011001110;
  assign Look_Up_Table_1[419] = 17'sb00111101011101010;
  assign Look_Up_Table_1[420] = 17'sb00111101100000110;
  assign Look_Up_Table_1[421] = 17'sb00111101100100010;
  assign Look_Up_Table_1[422] = 17'sb00111101100111101;
  assign Look_Up_Table_1[423] = 17'sb00111101101011000;
  assign Look_Up_Table_1[424] = 17'sb00111101101110011;
  assign Look_Up_Table_1[425] = 17'sb00111101110001110;
  assign Look_Up_Table_1[426] = 17'sb00111101110101000;
  assign Look_Up_Table_1[427] = 17'sb00111101111000010;
  assign Look_Up_Table_1[428] = 17'sb00111101111011011;
  assign Look_Up_Table_1[429] = 17'sb00111101111110101;
  assign Look_Up_Table_1[430] = 17'sb00111110000001101;
  assign Look_Up_Table_1[431] = 17'sb00111110000100110;
  assign Look_Up_Table_1[432] = 17'sb00111110000111111;
  assign Look_Up_Table_1[433] = 17'sb00111110001010111;
  assign Look_Up_Table_1[434] = 17'sb00111110001101110;
  assign Look_Up_Table_1[435] = 17'sb00111110010000110;
  assign Look_Up_Table_1[436] = 17'sb00111110010011101;
  assign Look_Up_Table_1[437] = 17'sb00111110010110100;
  assign Look_Up_Table_1[438] = 17'sb00111110011001010;
  assign Look_Up_Table_1[439] = 17'sb00111110011100001;
  assign Look_Up_Table_1[440] = 17'sb00111110011110111;
  assign Look_Up_Table_1[441] = 17'sb00111110100001100;
  assign Look_Up_Table_1[442] = 17'sb00111110100100010;
  assign Look_Up_Table_1[443] = 17'sb00111110100110111;
  assign Look_Up_Table_1[444] = 17'sb00111110101001011;
  assign Look_Up_Table_1[445] = 17'sb00111110101100000;
  assign Look_Up_Table_1[446] = 17'sb00111110101110100;
  assign Look_Up_Table_1[447] = 17'sb00111110110001000;
  assign Look_Up_Table_1[448] = 17'sb00111110110011011;
  assign Look_Up_Table_1[449] = 17'sb00111110110101111;
  assign Look_Up_Table_1[450] = 17'sb00111110111000010;
  assign Look_Up_Table_1[451] = 17'sb00111110111010100;
  assign Look_Up_Table_1[452] = 17'sb00111110111100111;
  assign Look_Up_Table_1[453] = 17'sb00111110111111001;
  assign Look_Up_Table_1[454] = 17'sb00111111000001010;
  assign Look_Up_Table_1[455] = 17'sb00111111000011100;
  assign Look_Up_Table_1[456] = 17'sb00111111000101101;
  assign Look_Up_Table_1[457] = 17'sb00111111000111110;
  assign Look_Up_Table_1[458] = 17'sb00111111001001110;
  assign Look_Up_Table_1[459] = 17'sb00111111001011110;
  assign Look_Up_Table_1[460] = 17'sb00111111001101110;
  assign Look_Up_Table_1[461] = 17'sb00111111001111110;
  assign Look_Up_Table_1[462] = 17'sb00111111010001101;
  assign Look_Up_Table_1[463] = 17'sb00111111010011100;
  assign Look_Up_Table_1[464] = 17'sb00111111010101011;
  assign Look_Up_Table_1[465] = 17'sb00111111010111001;
  assign Look_Up_Table_1[466] = 17'sb00111111011000111;
  assign Look_Up_Table_1[467] = 17'sb00111111011010101;
  assign Look_Up_Table_1[468] = 17'sb00111111011100010;
  assign Look_Up_Table_1[469] = 17'sb00111111011101111;
  assign Look_Up_Table_1[470] = 17'sb00111111011111100;
  assign Look_Up_Table_1[471] = 17'sb00111111100001001;
  assign Look_Up_Table_1[472] = 17'sb00111111100010101;
  assign Look_Up_Table_1[473] = 17'sb00111111100100001;
  assign Look_Up_Table_1[474] = 17'sb00111111100101100;
  assign Look_Up_Table_1[475] = 17'sb00111111100111000;
  assign Look_Up_Table_1[476] = 17'sb00111111101000011;
  assign Look_Up_Table_1[477] = 17'sb00111111101001101;
  assign Look_Up_Table_1[478] = 17'sb00111111101011000;
  assign Look_Up_Table_1[479] = 17'sb00111111101100010;
  assign Look_Up_Table_1[480] = 17'sb00111111101101011;
  assign Look_Up_Table_1[481] = 17'sb00111111101110101;
  assign Look_Up_Table_1[482] = 17'sb00111111101111110;
  assign Look_Up_Table_1[483] = 17'sb00111111110000111;
  assign Look_Up_Table_1[484] = 17'sb00111111110001111;
  assign Look_Up_Table_1[485] = 17'sb00111111110010111;
  assign Look_Up_Table_1[486] = 17'sb00111111110011111;
  assign Look_Up_Table_1[487] = 17'sb00111111110100111;
  assign Look_Up_Table_1[488] = 17'sb00111111110101110;
  assign Look_Up_Table_1[489] = 17'sb00111111110110101;
  assign Look_Up_Table_1[490] = 17'sb00111111110111100;
  assign Look_Up_Table_1[491] = 17'sb00111111111000010;
  assign Look_Up_Table_1[492] = 17'sb00111111111001000;
  assign Look_Up_Table_1[493] = 17'sb00111111111001110;
  assign Look_Up_Table_1[494] = 17'sb00111111111010011;
  assign Look_Up_Table_1[495] = 17'sb00111111111011000;
  assign Look_Up_Table_1[496] = 17'sb00111111111011101;
  assign Look_Up_Table_1[497] = 17'sb00111111111100010;
  assign Look_Up_Table_1[498] = 17'sb00111111111100110;
  assign Look_Up_Table_1[499] = 17'sb00111111111101010;
  assign Look_Up_Table_1[500] = 17'sb00111111111101101;
  assign Look_Up_Table_1[501] = 17'sb00111111111110001;
  assign Look_Up_Table_1[502] = 17'sb00111111111110011;
  assign Look_Up_Table_1[503] = 17'sb00111111111110110;
  assign Look_Up_Table_1[504] = 17'sb00111111111111000;
  assign Look_Up_Table_1[505] = 17'sb00111111111111010;
  assign Look_Up_Table_1[506] = 17'sb00111111111111100;
  assign Look_Up_Table_1[507] = 17'sb00111111111111110;
  assign Look_Up_Table_1[508] = 17'sb00111111111111111;
  assign Look_Up_Table_1[509] = 17'sb00111111111111111;
  assign Look_Up_Table_1[510] = 17'sb01000000000000000;
  assign Look_Up_Table_1[511] = 17'sb01000000000000000;
  assign Look_Up_Table_out1 = Look_Up_Table_1[prelookup_idx];

  always @(posedge clk)
    begin : Unit_Delay1_process
      if (enb) begin
        Unit_Delay_out1 <= Look_Up_Table_out1;
      end
    end

  assign Negate1_cast = {Unit_Delay_out1[16], Unit_Delay_out1};
  assign Negate1_cast_1 =  - (Negate1_cast);
  assign Negate_out1 = Negate1_cast_1[16:0];

  assign Sine = (RAMDelayBalance_out1 == 1'b0 ? Negate_out1 :
              Unit_Delay_out1);

  assign x = Sine;

  assign insig_out1_1 = u[11:1];

  assign Point25_out1_1 = 17'b01000000000000000;

  assign LTEp25_cast = {insig_out1_1, 6'b000000};
  assign LTEp25_out1_1 = LTEp25_cast <= Point25_out1_1;

  assign Point75_out1 = 17'b11000000000000000;

  assign GTEp75_cast = {insig_out1_1, 6'b000000};
  assign GTEp75_out1 = GTEp75_cast >= Point75_out1;

  assign alpha1st_or_4th_Quad_bool = LTEp25_out1_1 | GTEp75_out1;

  assign alpha1st_or_4th_Quad_out1 = {7'b0, alpha1st_or_4th_Quad_bool};

  always @(posedge clk)
    begin : RAMDelayBalance_process
      if (reset == 1'b0) begin
        RAMDelayBalance_out1_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          RAMDelayBalance_out1_1 <= alpha1st_or_4th_Quad_out1;
        end
      end
    end

  assign pow2switch_out1_1 = 1'b1;

  assign Point50_out1_1 = 17'b10000000000000000;

  assign p75mA_sub_cast = {1'b0, Point75_out1};
  assign p75mA_sub_cast_1 = {1'b0, {insig_out1_1, 6'b000000}};
  assign p75mA_out1 = p75mA_sub_cast - p75mA_sub_cast_1;

  assign Amp75_sub_cast = {1'b0, {insig_out1_1, 6'b000000}};
  assign Amp75_sub_cast_1 = {1'b0, Point75_out1};
  assign Amp75_out1 = Amp75_sub_cast - Amp75_sub_cast_1;

  assign Amp25_sub_cast = {1'b0, {insig_out1_1, 6'b000000}};
  assign Amp25_sub_cast_1 = {1'b0, Point25_out1_1};
  assign Amp25_out1 = Amp25_sub_cast - Amp25_sub_cast_1;

  assign p25mA_sub_cast = {1'b0, Point25_out1_1};
  assign p25mA_sub_cast_1 = {1'b0, {insig_out1_1, 6'b000000}};
  assign p25mA_out1 = p25mA_sub_cast - p25mA_sub_cast_1;

  assign LTEp50_cast = {insig_out1_1, 6'b000000};
  assign LTEp50_out1_1 = LTEp50_cast <= Point50_out1_1;

  assign QuadHandle1b_out1 = (GTEp75_out1 == 1'b0 ? p75mA_out1 :
              Amp75_out1);

  assign QuadHandle1b_out1_dtc = ((QuadHandle1b_out1[17] == 1'b0) && (QuadHandle1b_out1[16:6] == 11'b11111111111) ? 11'b11111111111 :
              (QuadHandle1b_out1[17] == 1'b1 ? 11'b00000000000 :
              QuadHandle1b_out1[16:6]));

  assign QuadHandle1a_out1 = (LTEp25_out1_1 == 1'b0 ? Amp25_out1 :
              p25mA_out1);

  assign QuadHandle1a_out1_dtc = ((QuadHandle1a_out1[17] == 1'b0) && (QuadHandle1a_out1[16:6] == 11'b11111111111) ? 11'b11111111111 :
              (QuadHandle1a_out1[17] == 1'b1 ? 11'b00000000000 :
              QuadHandle1a_out1[16:6]));

  assign QuadHandle2_out1_1 = (LTEp50_out1_1 == 1'b0 ? QuadHandle1b_out1_dtc :
              QuadHandle1a_out1_dtc);

  assign CastU16En1_out1 = QuadHandle2_out1_1;

  assign CastU16En3_out1_1 = {1'b0, CastU16En1_out1};

  assign CastU16En2_out1_1 = (CastU16En3_out1_1[11] != 1'b0 ? 11'b11111111111 :
              CastU16En3_out1_1[10:0]);

  assign UpperLimit_out_1 = 11'b00111111111;

  assign Sat_UpperRelOp_out_1 = CastU16En2_out1_1 > UpperLimit_out_1;

  assign LowerLimit_out_1 = 11'b00000000000;

  assign Sat_LowerRelOp_out_1 = CastU16En2_out1_1 < LowerLimit_out_1;

  assign Sat_LowerSwitch_out_1 = (Sat_LowerRelOp_out_1 == 1'b0 ? CastU16En2_out1_1 :
              LowerLimit_out_1);

  assign Saturation_out1_1 = (Sat_UpperRelOp_out_1 == 1'b0 ? Sat_LowerSwitch_out_1 :
              UpperLimit_out_1);

  assign Switch_out1_1 = (pow2switch_out1_1 == 1'b0 ? CastU16En2_out1_1 :
              Saturation_out1_1);

  assign prelookup_idx_1 = (Switch_out1_1 == 11'b00000000000 ? 9'b000000000 :
              (Switch_out1_1 >= 11'b00111111111 ? 9'b111111111 :
              Switch_out1_1[8:0]));

  assign Look_Up_Table_3[0] = 17'sb00000000000000000;
  assign Look_Up_Table_3[1] = 17'sb00000000001100101;
  assign Look_Up_Table_3[2] = 17'sb00000000011001001;
  assign Look_Up_Table_3[3] = 17'sb00000000100101110;
  assign Look_Up_Table_3[4] = 17'sb00000000110010011;
  assign Look_Up_Table_3[5] = 17'sb00000000111111000;
  assign Look_Up_Table_3[6] = 17'sb00000001001011100;
  assign Look_Up_Table_3[7] = 17'sb00000001011000001;
  assign Look_Up_Table_3[8] = 17'sb00000001100100110;
  assign Look_Up_Table_3[9] = 17'sb00000001110001010;
  assign Look_Up_Table_3[10] = 17'sb00000001111101111;
  assign Look_Up_Table_3[11] = 17'sb00000010001010100;
  assign Look_Up_Table_3[12] = 17'sb00000010010111000;
  assign Look_Up_Table_3[13] = 17'sb00000010100011101;
  assign Look_Up_Table_3[14] = 17'sb00000010110000010;
  assign Look_Up_Table_3[15] = 17'sb00000010111100110;
  assign Look_Up_Table_3[16] = 17'sb00000011001001011;
  assign Look_Up_Table_3[17] = 17'sb00000011010110000;
  assign Look_Up_Table_3[18] = 17'sb00000011100010100;
  assign Look_Up_Table_3[19] = 17'sb00000011101111001;
  assign Look_Up_Table_3[20] = 17'sb00000011111011101;
  assign Look_Up_Table_3[21] = 17'sb00000100001000010;
  assign Look_Up_Table_3[22] = 17'sb00000100010100110;
  assign Look_Up_Table_3[23] = 17'sb00000100100001011;
  assign Look_Up_Table_3[24] = 17'sb00000100101101111;
  assign Look_Up_Table_3[25] = 17'sb00000100111010100;
  assign Look_Up_Table_3[26] = 17'sb00000101000111000;
  assign Look_Up_Table_3[27] = 17'sb00000101010011101;
  assign Look_Up_Table_3[28] = 17'sb00000101100000001;
  assign Look_Up_Table_3[29] = 17'sb00000101101100101;
  assign Look_Up_Table_3[30] = 17'sb00000101111001010;
  assign Look_Up_Table_3[31] = 17'sb00000110000101110;
  assign Look_Up_Table_3[32] = 17'sb00000110010010010;
  assign Look_Up_Table_3[33] = 17'sb00000110011110110;
  assign Look_Up_Table_3[34] = 17'sb00000110101011011;
  assign Look_Up_Table_3[35] = 17'sb00000110110111111;
  assign Look_Up_Table_3[36] = 17'sb00000111000100011;
  assign Look_Up_Table_3[37] = 17'sb00000111010000111;
  assign Look_Up_Table_3[38] = 17'sb00000111011101011;
  assign Look_Up_Table_3[39] = 17'sb00000111101001111;
  assign Look_Up_Table_3[40] = 17'sb00000111110110011;
  assign Look_Up_Table_3[41] = 17'sb00001000000010111;
  assign Look_Up_Table_3[42] = 17'sb00001000001111011;
  assign Look_Up_Table_3[43] = 17'sb00001000011011111;
  assign Look_Up_Table_3[44] = 17'sb00001000101000011;
  assign Look_Up_Table_3[45] = 17'sb00001000110100110;
  assign Look_Up_Table_3[46] = 17'sb00001001000001010;
  assign Look_Up_Table_3[47] = 17'sb00001001001101110;
  assign Look_Up_Table_3[48] = 17'sb00001001011010001;
  assign Look_Up_Table_3[49] = 17'sb00001001100110101;
  assign Look_Up_Table_3[50] = 17'sb00001001110011001;
  assign Look_Up_Table_3[51] = 17'sb00001001111111100;
  assign Look_Up_Table_3[52] = 17'sb00001010001100000;
  assign Look_Up_Table_3[53] = 17'sb00001010011000011;
  assign Look_Up_Table_3[54] = 17'sb00001010100100110;
  assign Look_Up_Table_3[55] = 17'sb00001010110001010;
  assign Look_Up_Table_3[56] = 17'sb00001010111101101;
  assign Look_Up_Table_3[57] = 17'sb00001011001010000;
  assign Look_Up_Table_3[58] = 17'sb00001011010110011;
  assign Look_Up_Table_3[59] = 17'sb00001011100010110;
  assign Look_Up_Table_3[60] = 17'sb00001011101111001;
  assign Look_Up_Table_3[61] = 17'sb00001011111011100;
  assign Look_Up_Table_3[62] = 17'sb00001100000111111;
  assign Look_Up_Table_3[63] = 17'sb00001100010100010;
  assign Look_Up_Table_3[64] = 17'sb00001100100000101;
  assign Look_Up_Table_3[65] = 17'sb00001100101101000;
  assign Look_Up_Table_3[66] = 17'sb00001100111001011;
  assign Look_Up_Table_3[67] = 17'sb00001101000101101;
  assign Look_Up_Table_3[68] = 17'sb00001101010010000;
  assign Look_Up_Table_3[69] = 17'sb00001101011110010;
  assign Look_Up_Table_3[70] = 17'sb00001101101010101;
  assign Look_Up_Table_3[71] = 17'sb00001101110110111;
  assign Look_Up_Table_3[72] = 17'sb00001110000011001;
  assign Look_Up_Table_3[73] = 17'sb00001110001111100;
  assign Look_Up_Table_3[74] = 17'sb00001110011011110;
  assign Look_Up_Table_3[75] = 17'sb00001110101000000;
  assign Look_Up_Table_3[76] = 17'sb00001110110100010;
  assign Look_Up_Table_3[77] = 17'sb00001111000000100;
  assign Look_Up_Table_3[78] = 17'sb00001111001100110;
  assign Look_Up_Table_3[79] = 17'sb00001111011001000;
  assign Look_Up_Table_3[80] = 17'sb00001111100101001;
  assign Look_Up_Table_3[81] = 17'sb00001111110001011;
  assign Look_Up_Table_3[82] = 17'sb00001111111101100;
  assign Look_Up_Table_3[83] = 17'sb00010000001001110;
  assign Look_Up_Table_3[84] = 17'sb00010000010101111;
  assign Look_Up_Table_3[85] = 17'sb00010000100010001;
  assign Look_Up_Table_3[86] = 17'sb00010000101110010;
  assign Look_Up_Table_3[87] = 17'sb00010000111010011;
  assign Look_Up_Table_3[88] = 17'sb00010001000110100;
  assign Look_Up_Table_3[89] = 17'sb00010001010010101;
  assign Look_Up_Table_3[90] = 17'sb00010001011110110;
  assign Look_Up_Table_3[91] = 17'sb00010001101010111;
  assign Look_Up_Table_3[92] = 17'sb00010001110111000;
  assign Look_Up_Table_3[93] = 17'sb00010010000011001;
  assign Look_Up_Table_3[94] = 17'sb00010010001111001;
  assign Look_Up_Table_3[95] = 17'sb00010010011011010;
  assign Look_Up_Table_3[96] = 17'sb00010010100111010;
  assign Look_Up_Table_3[97] = 17'sb00010010110011010;
  assign Look_Up_Table_3[98] = 17'sb00010010111111011;
  assign Look_Up_Table_3[99] = 17'sb00010011001011011;
  assign Look_Up_Table_3[100] = 17'sb00010011010111011;
  assign Look_Up_Table_3[101] = 17'sb00010011100011011;
  assign Look_Up_Table_3[102] = 17'sb00010011101111011;
  assign Look_Up_Table_3[103] = 17'sb00010011111011010;
  assign Look_Up_Table_3[104] = 17'sb00010100000111010;
  assign Look_Up_Table_3[105] = 17'sb00010100010011010;
  assign Look_Up_Table_3[106] = 17'sb00010100011111001;
  assign Look_Up_Table_3[107] = 17'sb00010100101011001;
  assign Look_Up_Table_3[108] = 17'sb00010100110111000;
  assign Look_Up_Table_3[109] = 17'sb00010101000010111;
  assign Look_Up_Table_3[110] = 17'sb00010101001110110;
  assign Look_Up_Table_3[111] = 17'sb00010101011010101;
  assign Look_Up_Table_3[112] = 17'sb00010101100110100;
  assign Look_Up_Table_3[113] = 17'sb00010101110010011;
  assign Look_Up_Table_3[114] = 17'sb00010101111110001;
  assign Look_Up_Table_3[115] = 17'sb00010110001010000;
  assign Look_Up_Table_3[116] = 17'sb00010110010101110;
  assign Look_Up_Table_3[117] = 17'sb00010110100001101;
  assign Look_Up_Table_3[118] = 17'sb00010110101101011;
  assign Look_Up_Table_3[119] = 17'sb00010110111001001;
  assign Look_Up_Table_3[120] = 17'sb00010111000100111;
  assign Look_Up_Table_3[121] = 17'sb00010111010000101;
  assign Look_Up_Table_3[122] = 17'sb00010111011100011;
  assign Look_Up_Table_3[123] = 17'sb00010111101000000;
  assign Look_Up_Table_3[124] = 17'sb00010111110011110;
  assign Look_Up_Table_3[125] = 17'sb00010111111111011;
  assign Look_Up_Table_3[126] = 17'sb00011000001011001;
  assign Look_Up_Table_3[127] = 17'sb00011000010110110;
  assign Look_Up_Table_3[128] = 17'sb00011000100010011;
  assign Look_Up_Table_3[129] = 17'sb00011000101110000;
  assign Look_Up_Table_3[130] = 17'sb00011000111001101;
  assign Look_Up_Table_3[131] = 17'sb00011001000101010;
  assign Look_Up_Table_3[132] = 17'sb00011001010000110;
  assign Look_Up_Table_3[133] = 17'sb00011001011100011;
  assign Look_Up_Table_3[134] = 17'sb00011001100111111;
  assign Look_Up_Table_3[135] = 17'sb00011001110011011;
  assign Look_Up_Table_3[136] = 17'sb00011001111110111;
  assign Look_Up_Table_3[137] = 17'sb00011010001010011;
  assign Look_Up_Table_3[138] = 17'sb00011010010101111;
  assign Look_Up_Table_3[139] = 17'sb00011010100001011;
  assign Look_Up_Table_3[140] = 17'sb00011010101100111;
  assign Look_Up_Table_3[141] = 17'sb00011010111000010;
  assign Look_Up_Table_3[142] = 17'sb00011011000011101;
  assign Look_Up_Table_3[143] = 17'sb00011011001111001;
  assign Look_Up_Table_3[144] = 17'sb00011011011010100;
  assign Look_Up_Table_3[145] = 17'sb00011011100101111;
  assign Look_Up_Table_3[146] = 17'sb00011011110001010;
  assign Look_Up_Table_3[147] = 17'sb00011011111100100;
  assign Look_Up_Table_3[148] = 17'sb00011100000111111;
  assign Look_Up_Table_3[149] = 17'sb00011100010011001;
  assign Look_Up_Table_3[150] = 17'sb00011100011110011;
  assign Look_Up_Table_3[151] = 17'sb00011100101001110;
  assign Look_Up_Table_3[152] = 17'sb00011100110101000;
  assign Look_Up_Table_3[153] = 17'sb00011101000000001;
  assign Look_Up_Table_3[154] = 17'sb00011101001011011;
  assign Look_Up_Table_3[155] = 17'sb00011101010110101;
  assign Look_Up_Table_3[156] = 17'sb00011101100001110;
  assign Look_Up_Table_3[157] = 17'sb00011101101100111;
  assign Look_Up_Table_3[158] = 17'sb00011101111000001;
  assign Look_Up_Table_3[159] = 17'sb00011110000011010;
  assign Look_Up_Table_3[160] = 17'sb00011110001110010;
  assign Look_Up_Table_3[161] = 17'sb00011110011001011;
  assign Look_Up_Table_3[162] = 17'sb00011110100100100;
  assign Look_Up_Table_3[163] = 17'sb00011110101111100;
  assign Look_Up_Table_3[164] = 17'sb00011110111010100;
  assign Look_Up_Table_3[165] = 17'sb00011111000101101;
  assign Look_Up_Table_3[166] = 17'sb00011111010000101;
  assign Look_Up_Table_3[167] = 17'sb00011111011011100;
  assign Look_Up_Table_3[168] = 17'sb00011111100110100;
  assign Look_Up_Table_3[169] = 17'sb00011111110001100;
  assign Look_Up_Table_3[170] = 17'sb00011111111100011;
  assign Look_Up_Table_3[171] = 17'sb00100000000111010;
  assign Look_Up_Table_3[172] = 17'sb00100000010010001;
  assign Look_Up_Table_3[173] = 17'sb00100000011101000;
  assign Look_Up_Table_3[174] = 17'sb00100000100111111;
  assign Look_Up_Table_3[175] = 17'sb00100000110010101;
  assign Look_Up_Table_3[176] = 17'sb00100000111101100;
  assign Look_Up_Table_3[177] = 17'sb00100001001000010;
  assign Look_Up_Table_3[178] = 17'sb00100001010011000;
  assign Look_Up_Table_3[179] = 17'sb00100001011101110;
  assign Look_Up_Table_3[180] = 17'sb00100001101000100;
  assign Look_Up_Table_3[181] = 17'sb00100001110011010;
  assign Look_Up_Table_3[182] = 17'sb00100001111101111;
  assign Look_Up_Table_3[183] = 17'sb00100010001000100;
  assign Look_Up_Table_3[184] = 17'sb00100010010011001;
  assign Look_Up_Table_3[185] = 17'sb00100010011101110;
  assign Look_Up_Table_3[186] = 17'sb00100010101000011;
  assign Look_Up_Table_3[187] = 17'sb00100010110011000;
  assign Look_Up_Table_3[188] = 17'sb00100010111101100;
  assign Look_Up_Table_3[189] = 17'sb00100011001000000;
  assign Look_Up_Table_3[190] = 17'sb00100011010010101;
  assign Look_Up_Table_3[191] = 17'sb00100011011101001;
  assign Look_Up_Table_3[192] = 17'sb00100011100111100;
  assign Look_Up_Table_3[193] = 17'sb00100011110010000;
  assign Look_Up_Table_3[194] = 17'sb00100011111100011;
  assign Look_Up_Table_3[195] = 17'sb00100100000110111;
  assign Look_Up_Table_3[196] = 17'sb00100100010001010;
  assign Look_Up_Table_3[197] = 17'sb00100100011011101;
  assign Look_Up_Table_3[198] = 17'sb00100100100101111;
  assign Look_Up_Table_3[199] = 17'sb00100100110000010;
  assign Look_Up_Table_3[200] = 17'sb00100100111010100;
  assign Look_Up_Table_3[201] = 17'sb00100101000100110;
  assign Look_Up_Table_3[202] = 17'sb00100101001111000;
  assign Look_Up_Table_3[203] = 17'sb00100101011001010;
  assign Look_Up_Table_3[204] = 17'sb00100101100011100;
  assign Look_Up_Table_3[205] = 17'sb00100101101101101;
  assign Look_Up_Table_3[206] = 17'sb00100101110111111;
  assign Look_Up_Table_3[207] = 17'sb00100110000010000;
  assign Look_Up_Table_3[208] = 17'sb00100110001100001;
  assign Look_Up_Table_3[209] = 17'sb00100110010110001;
  assign Look_Up_Table_3[210] = 17'sb00100110100000010;
  assign Look_Up_Table_3[211] = 17'sb00100110101010010;
  assign Look_Up_Table_3[212] = 17'sb00100110110100011;
  assign Look_Up_Table_3[213] = 17'sb00100110111110011;
  assign Look_Up_Table_3[214] = 17'sb00100111001000010;
  assign Look_Up_Table_3[215] = 17'sb00100111010010010;
  assign Look_Up_Table_3[216] = 17'sb00100111011100001;
  assign Look_Up_Table_3[217] = 17'sb00100111100110001;
  assign Look_Up_Table_3[218] = 17'sb00100111110000000;
  assign Look_Up_Table_3[219] = 17'sb00100111111001111;
  assign Look_Up_Table_3[220] = 17'sb00101000000011101;
  assign Look_Up_Table_3[221] = 17'sb00101000001101100;
  assign Look_Up_Table_3[222] = 17'sb00101000010111010;
  assign Look_Up_Table_3[223] = 17'sb00101000100001000;
  assign Look_Up_Table_3[224] = 17'sb00101000101010110;
  assign Look_Up_Table_3[225] = 17'sb00101000110100100;
  assign Look_Up_Table_3[226] = 17'sb00101000111110001;
  assign Look_Up_Table_3[227] = 17'sb00101001000111110;
  assign Look_Up_Table_3[228] = 17'sb00101001010001011;
  assign Look_Up_Table_3[229] = 17'sb00101001011011000;
  assign Look_Up_Table_3[230] = 17'sb00101001100100101;
  assign Look_Up_Table_3[231] = 17'sb00101001101110001;
  assign Look_Up_Table_3[232] = 17'sb00101001110111110;
  assign Look_Up_Table_3[233] = 17'sb00101010000001010;
  assign Look_Up_Table_3[234] = 17'sb00101010001010110;
  assign Look_Up_Table_3[235] = 17'sb00101010010100001;
  assign Look_Up_Table_3[236] = 17'sb00101010011101101;
  assign Look_Up_Table_3[237] = 17'sb00101010100111000;
  assign Look_Up_Table_3[238] = 17'sb00101010110000011;
  assign Look_Up_Table_3[239] = 17'sb00101010111001110;
  assign Look_Up_Table_3[240] = 17'sb00101011000011001;
  assign Look_Up_Table_3[241] = 17'sb00101011001100011;
  assign Look_Up_Table_3[242] = 17'sb00101011010101101;
  assign Look_Up_Table_3[243] = 17'sb00101011011110111;
  assign Look_Up_Table_3[244] = 17'sb00101011101000001;
  assign Look_Up_Table_3[245] = 17'sb00101011110001011;
  assign Look_Up_Table_3[246] = 17'sb00101011111010100;
  assign Look_Up_Table_3[247] = 17'sb00101100000011101;
  assign Look_Up_Table_3[248] = 17'sb00101100001100110;
  assign Look_Up_Table_3[249] = 17'sb00101100010101111;
  assign Look_Up_Table_3[250] = 17'sb00101100011110111;
  assign Look_Up_Table_3[251] = 17'sb00101100101000000;
  assign Look_Up_Table_3[252] = 17'sb00101100110001000;
  assign Look_Up_Table_3[253] = 17'sb00101100111010000;
  assign Look_Up_Table_3[254] = 17'sb00101101000010111;
  assign Look_Up_Table_3[255] = 17'sb00101101001011111;
  assign Look_Up_Table_3[256] = 17'sb00101101010100110;
  assign Look_Up_Table_3[257] = 17'sb00101101011101101;
  assign Look_Up_Table_3[258] = 17'sb00101101100110100;
  assign Look_Up_Table_3[259] = 17'sb00101101101111010;
  assign Look_Up_Table_3[260] = 17'sb00101101111000001;
  assign Look_Up_Table_3[261] = 17'sb00101110000000111;
  assign Look_Up_Table_3[262] = 17'sb00101110001001101;
  assign Look_Up_Table_3[263] = 17'sb00101110010010010;
  assign Look_Up_Table_3[264] = 17'sb00101110011011000;
  assign Look_Up_Table_3[265] = 17'sb00101110100011101;
  assign Look_Up_Table_3[266] = 17'sb00101110101100010;
  assign Look_Up_Table_3[267] = 17'sb00101110110100111;
  assign Look_Up_Table_3[268] = 17'sb00101110111101011;
  assign Look_Up_Table_3[269] = 17'sb00101111000110000;
  assign Look_Up_Table_3[270] = 17'sb00101111001110100;
  assign Look_Up_Table_3[271] = 17'sb00101111010111000;
  assign Look_Up_Table_3[272] = 17'sb00101111011111011;
  assign Look_Up_Table_3[273] = 17'sb00101111100111111;
  assign Look_Up_Table_3[274] = 17'sb00101111110000010;
  assign Look_Up_Table_3[275] = 17'sb00101111111000101;
  assign Look_Up_Table_3[276] = 17'sb00110000000001000;
  assign Look_Up_Table_3[277] = 17'sb00110000001001010;
  assign Look_Up_Table_3[278] = 17'sb00110000010001100;
  assign Look_Up_Table_3[279] = 17'sb00110000011001110;
  assign Look_Up_Table_3[280] = 17'sb00110000100010000;
  assign Look_Up_Table_3[281] = 17'sb00110000101010010;
  assign Look_Up_Table_3[282] = 17'sb00110000110010011;
  assign Look_Up_Table_3[283] = 17'sb00110000111010100;
  assign Look_Up_Table_3[284] = 17'sb00110001000010101;
  assign Look_Up_Table_3[285] = 17'sb00110001001010110;
  assign Look_Up_Table_3[286] = 17'sb00110001010010110;
  assign Look_Up_Table_3[287] = 17'sb00110001011010110;
  assign Look_Up_Table_3[288] = 17'sb00110001100010110;
  assign Look_Up_Table_3[289] = 17'sb00110001101010110;
  assign Look_Up_Table_3[290] = 17'sb00110001110010101;
  assign Look_Up_Table_3[291] = 17'sb00110001111010100;
  assign Look_Up_Table_3[292] = 17'sb00110010000010011;
  assign Look_Up_Table_3[293] = 17'sb00110010001010010;
  assign Look_Up_Table_3[294] = 17'sb00110010010010000;
  assign Look_Up_Table_3[295] = 17'sb00110010011001110;
  assign Look_Up_Table_3[296] = 17'sb00110010100001100;
  assign Look_Up_Table_3[297] = 17'sb00110010101001010;
  assign Look_Up_Table_3[298] = 17'sb00110010110000111;
  assign Look_Up_Table_3[299] = 17'sb00110010111000101;
  assign Look_Up_Table_3[300] = 17'sb00110011000000010;
  assign Look_Up_Table_3[301] = 17'sb00110011000111110;
  assign Look_Up_Table_3[302] = 17'sb00110011001111011;
  assign Look_Up_Table_3[303] = 17'sb00110011010110111;
  assign Look_Up_Table_3[304] = 17'sb00110011011110011;
  assign Look_Up_Table_3[305] = 17'sb00110011100101111;
  assign Look_Up_Table_3[306] = 17'sb00110011101101010;
  assign Look_Up_Table_3[307] = 17'sb00110011110100110;
  assign Look_Up_Table_3[308] = 17'sb00110011111100001;
  assign Look_Up_Table_3[309] = 17'sb00110100000011011;
  assign Look_Up_Table_3[310] = 17'sb00110100001010110;
  assign Look_Up_Table_3[311] = 17'sb00110100010010000;
  assign Look_Up_Table_3[312] = 17'sb00110100011001010;
  assign Look_Up_Table_3[313] = 17'sb00110100100000100;
  assign Look_Up_Table_3[314] = 17'sb00110100100111101;
  assign Look_Up_Table_3[315] = 17'sb00110100101110110;
  assign Look_Up_Table_3[316] = 17'sb00110100110101111;
  assign Look_Up_Table_3[317] = 17'sb00110100111101000;
  assign Look_Up_Table_3[318] = 17'sb00110101000100000;
  assign Look_Up_Table_3[319] = 17'sb00110101001011001;
  assign Look_Up_Table_3[320] = 17'sb00110101010010001;
  assign Look_Up_Table_3[321] = 17'sb00110101011001000;
  assign Look_Up_Table_3[322] = 17'sb00110101100000000;
  assign Look_Up_Table_3[323] = 17'sb00110101100110111;
  assign Look_Up_Table_3[324] = 17'sb00110101101101110;
  assign Look_Up_Table_3[325] = 17'sb00110101110100100;
  assign Look_Up_Table_3[326] = 17'sb00110101111011011;
  assign Look_Up_Table_3[327] = 17'sb00110110000010001;
  assign Look_Up_Table_3[328] = 17'sb00110110001000111;
  assign Look_Up_Table_3[329] = 17'sb00110110001111100;
  assign Look_Up_Table_3[330] = 17'sb00110110010110010;
  assign Look_Up_Table_3[331] = 17'sb00110110011100111;
  assign Look_Up_Table_3[332] = 17'sb00110110100011011;
  assign Look_Up_Table_3[333] = 17'sb00110110101010000;
  assign Look_Up_Table_3[334] = 17'sb00110110110000100;
  assign Look_Up_Table_3[335] = 17'sb00110110110111000;
  assign Look_Up_Table_3[336] = 17'sb00110110111101100;
  assign Look_Up_Table_3[337] = 17'sb00110111000011111;
  assign Look_Up_Table_3[338] = 17'sb00110111001010011;
  assign Look_Up_Table_3[339] = 17'sb00110111010000110;
  assign Look_Up_Table_3[340] = 17'sb00110111010111000;
  assign Look_Up_Table_3[341] = 17'sb00110111011101011;
  assign Look_Up_Table_3[342] = 17'sb00110111100011101;
  assign Look_Up_Table_3[343] = 17'sb00110111101001111;
  assign Look_Up_Table_3[344] = 17'sb00110111110000000;
  assign Look_Up_Table_3[345] = 17'sb00110111110110010;
  assign Look_Up_Table_3[346] = 17'sb00110111111100011;
  assign Look_Up_Table_3[347] = 17'sb00111000000010011;
  assign Look_Up_Table_3[348] = 17'sb00111000001000100;
  assign Look_Up_Table_3[349] = 17'sb00111000001110100;
  assign Look_Up_Table_3[350] = 17'sb00111000010100100;
  assign Look_Up_Table_3[351] = 17'sb00111000011010100;
  assign Look_Up_Table_3[352] = 17'sb00111000100000011;
  assign Look_Up_Table_3[353] = 17'sb00111000100110011;
  assign Look_Up_Table_3[354] = 17'sb00111000101100001;
  assign Look_Up_Table_3[355] = 17'sb00111000110010000;
  assign Look_Up_Table_3[356] = 17'sb00111000110111110;
  assign Look_Up_Table_3[357] = 17'sb00111000111101100;
  assign Look_Up_Table_3[358] = 17'sb00111001000011010;
  assign Look_Up_Table_3[359] = 17'sb00111001001001000;
  assign Look_Up_Table_3[360] = 17'sb00111001001110101;
  assign Look_Up_Table_3[361] = 17'sb00111001010100010;
  assign Look_Up_Table_3[362] = 17'sb00111001011001111;
  assign Look_Up_Table_3[363] = 17'sb00111001011111011;
  assign Look_Up_Table_3[364] = 17'sb00111001100100111;
  assign Look_Up_Table_3[365] = 17'sb00111001101010011;
  assign Look_Up_Table_3[366] = 17'sb00111001101111111;
  assign Look_Up_Table_3[367] = 17'sb00111001110101010;
  assign Look_Up_Table_3[368] = 17'sb00111001111010101;
  assign Look_Up_Table_3[369] = 17'sb00111010000000000;
  assign Look_Up_Table_3[370] = 17'sb00111010000101010;
  assign Look_Up_Table_3[371] = 17'sb00111010001010100;
  assign Look_Up_Table_3[372] = 17'sb00111010001111110;
  assign Look_Up_Table_3[373] = 17'sb00111010010101000;
  assign Look_Up_Table_3[374] = 17'sb00111010011010001;
  assign Look_Up_Table_3[375] = 17'sb00111010011111010;
  assign Look_Up_Table_3[376] = 17'sb00111010100100011;
  assign Look_Up_Table_3[377] = 17'sb00111010101001011;
  assign Look_Up_Table_3[378] = 17'sb00111010101110011;
  assign Look_Up_Table_3[379] = 17'sb00111010110011011;
  assign Look_Up_Table_3[380] = 17'sb00111010111000011;
  assign Look_Up_Table_3[381] = 17'sb00111010111101010;
  assign Look_Up_Table_3[382] = 17'sb00111011000010001;
  assign Look_Up_Table_3[383] = 17'sb00111011000111000;
  assign Look_Up_Table_3[384] = 17'sb00111011001011111;
  assign Look_Up_Table_3[385] = 17'sb00111011010000101;
  assign Look_Up_Table_3[386] = 17'sb00111011010101011;
  assign Look_Up_Table_3[387] = 17'sb00111011011010000;
  assign Look_Up_Table_3[388] = 17'sb00111011011110110;
  assign Look_Up_Table_3[389] = 17'sb00111011100011011;
  assign Look_Up_Table_3[390] = 17'sb00111011100111111;
  assign Look_Up_Table_3[391] = 17'sb00111011101100100;
  assign Look_Up_Table_3[392] = 17'sb00111011110001000;
  assign Look_Up_Table_3[393] = 17'sb00111011110101100;
  assign Look_Up_Table_3[394] = 17'sb00111011111001111;
  assign Look_Up_Table_3[395] = 17'sb00111011111110011;
  assign Look_Up_Table_3[396] = 17'sb00111100000010110;
  assign Look_Up_Table_3[397] = 17'sb00111100000111001;
  assign Look_Up_Table_3[398] = 17'sb00111100001011011;
  assign Look_Up_Table_3[399] = 17'sb00111100001111101;
  assign Look_Up_Table_3[400] = 17'sb00111100010011111;
  assign Look_Up_Table_3[401] = 17'sb00111100011000000;
  assign Look_Up_Table_3[402] = 17'sb00111100011100010;
  assign Look_Up_Table_3[403] = 17'sb00111100100000011;
  assign Look_Up_Table_3[404] = 17'sb00111100100100011;
  assign Look_Up_Table_3[405] = 17'sb00111100101000100;
  assign Look_Up_Table_3[406] = 17'sb00111100101100100;
  assign Look_Up_Table_3[407] = 17'sb00111100110000100;
  assign Look_Up_Table_3[408] = 17'sb00111100110100011;
  assign Look_Up_Table_3[409] = 17'sb00111100111000010;
  assign Look_Up_Table_3[410] = 17'sb00111100111100001;
  assign Look_Up_Table_3[411] = 17'sb00111101000000000;
  assign Look_Up_Table_3[412] = 17'sb00111101000011110;
  assign Look_Up_Table_3[413] = 17'sb00111101000111100;
  assign Look_Up_Table_3[414] = 17'sb00111101001011010;
  assign Look_Up_Table_3[415] = 17'sb00111101001111000;
  assign Look_Up_Table_3[416] = 17'sb00111101010010101;
  assign Look_Up_Table_3[417] = 17'sb00111101010110010;
  assign Look_Up_Table_3[418] = 17'sb00111101011001110;
  assign Look_Up_Table_3[419] = 17'sb00111101011101010;
  assign Look_Up_Table_3[420] = 17'sb00111101100000110;
  assign Look_Up_Table_3[421] = 17'sb00111101100100010;
  assign Look_Up_Table_3[422] = 17'sb00111101100111101;
  assign Look_Up_Table_3[423] = 17'sb00111101101011000;
  assign Look_Up_Table_3[424] = 17'sb00111101101110011;
  assign Look_Up_Table_3[425] = 17'sb00111101110001110;
  assign Look_Up_Table_3[426] = 17'sb00111101110101000;
  assign Look_Up_Table_3[427] = 17'sb00111101111000010;
  assign Look_Up_Table_3[428] = 17'sb00111101111011011;
  assign Look_Up_Table_3[429] = 17'sb00111101111110101;
  assign Look_Up_Table_3[430] = 17'sb00111110000001101;
  assign Look_Up_Table_3[431] = 17'sb00111110000100110;
  assign Look_Up_Table_3[432] = 17'sb00111110000111111;
  assign Look_Up_Table_3[433] = 17'sb00111110001010111;
  assign Look_Up_Table_3[434] = 17'sb00111110001101110;
  assign Look_Up_Table_3[435] = 17'sb00111110010000110;
  assign Look_Up_Table_3[436] = 17'sb00111110010011101;
  assign Look_Up_Table_3[437] = 17'sb00111110010110100;
  assign Look_Up_Table_3[438] = 17'sb00111110011001010;
  assign Look_Up_Table_3[439] = 17'sb00111110011100001;
  assign Look_Up_Table_3[440] = 17'sb00111110011110111;
  assign Look_Up_Table_3[441] = 17'sb00111110100001100;
  assign Look_Up_Table_3[442] = 17'sb00111110100100010;
  assign Look_Up_Table_3[443] = 17'sb00111110100110111;
  assign Look_Up_Table_3[444] = 17'sb00111110101001011;
  assign Look_Up_Table_3[445] = 17'sb00111110101100000;
  assign Look_Up_Table_3[446] = 17'sb00111110101110100;
  assign Look_Up_Table_3[447] = 17'sb00111110110001000;
  assign Look_Up_Table_3[448] = 17'sb00111110110011011;
  assign Look_Up_Table_3[449] = 17'sb00111110110101111;
  assign Look_Up_Table_3[450] = 17'sb00111110111000010;
  assign Look_Up_Table_3[451] = 17'sb00111110111010100;
  assign Look_Up_Table_3[452] = 17'sb00111110111100111;
  assign Look_Up_Table_3[453] = 17'sb00111110111111001;
  assign Look_Up_Table_3[454] = 17'sb00111111000001010;
  assign Look_Up_Table_3[455] = 17'sb00111111000011100;
  assign Look_Up_Table_3[456] = 17'sb00111111000101101;
  assign Look_Up_Table_3[457] = 17'sb00111111000111110;
  assign Look_Up_Table_3[458] = 17'sb00111111001001110;
  assign Look_Up_Table_3[459] = 17'sb00111111001011110;
  assign Look_Up_Table_3[460] = 17'sb00111111001101110;
  assign Look_Up_Table_3[461] = 17'sb00111111001111110;
  assign Look_Up_Table_3[462] = 17'sb00111111010001101;
  assign Look_Up_Table_3[463] = 17'sb00111111010011100;
  assign Look_Up_Table_3[464] = 17'sb00111111010101011;
  assign Look_Up_Table_3[465] = 17'sb00111111010111001;
  assign Look_Up_Table_3[466] = 17'sb00111111011000111;
  assign Look_Up_Table_3[467] = 17'sb00111111011010101;
  assign Look_Up_Table_3[468] = 17'sb00111111011100010;
  assign Look_Up_Table_3[469] = 17'sb00111111011101111;
  assign Look_Up_Table_3[470] = 17'sb00111111011111100;
  assign Look_Up_Table_3[471] = 17'sb00111111100001001;
  assign Look_Up_Table_3[472] = 17'sb00111111100010101;
  assign Look_Up_Table_3[473] = 17'sb00111111100100001;
  assign Look_Up_Table_3[474] = 17'sb00111111100101100;
  assign Look_Up_Table_3[475] = 17'sb00111111100111000;
  assign Look_Up_Table_3[476] = 17'sb00111111101000011;
  assign Look_Up_Table_3[477] = 17'sb00111111101001101;
  assign Look_Up_Table_3[478] = 17'sb00111111101011000;
  assign Look_Up_Table_3[479] = 17'sb00111111101100010;
  assign Look_Up_Table_3[480] = 17'sb00111111101101011;
  assign Look_Up_Table_3[481] = 17'sb00111111101110101;
  assign Look_Up_Table_3[482] = 17'sb00111111101111110;
  assign Look_Up_Table_3[483] = 17'sb00111111110000111;
  assign Look_Up_Table_3[484] = 17'sb00111111110001111;
  assign Look_Up_Table_3[485] = 17'sb00111111110010111;
  assign Look_Up_Table_3[486] = 17'sb00111111110011111;
  assign Look_Up_Table_3[487] = 17'sb00111111110100111;
  assign Look_Up_Table_3[488] = 17'sb00111111110101110;
  assign Look_Up_Table_3[489] = 17'sb00111111110110101;
  assign Look_Up_Table_3[490] = 17'sb00111111110111100;
  assign Look_Up_Table_3[491] = 17'sb00111111111000010;
  assign Look_Up_Table_3[492] = 17'sb00111111111001000;
  assign Look_Up_Table_3[493] = 17'sb00111111111001110;
  assign Look_Up_Table_3[494] = 17'sb00111111111010011;
  assign Look_Up_Table_3[495] = 17'sb00111111111011000;
  assign Look_Up_Table_3[496] = 17'sb00111111111011101;
  assign Look_Up_Table_3[497] = 17'sb00111111111100010;
  assign Look_Up_Table_3[498] = 17'sb00111111111100110;
  assign Look_Up_Table_3[499] = 17'sb00111111111101010;
  assign Look_Up_Table_3[500] = 17'sb00111111111101101;
  assign Look_Up_Table_3[501] = 17'sb00111111111110001;
  assign Look_Up_Table_3[502] = 17'sb00111111111110011;
  assign Look_Up_Table_3[503] = 17'sb00111111111110110;
  assign Look_Up_Table_3[504] = 17'sb00111111111111000;
  assign Look_Up_Table_3[505] = 17'sb00111111111111010;
  assign Look_Up_Table_3[506] = 17'sb00111111111111100;
  assign Look_Up_Table_3[507] = 17'sb00111111111111110;
  assign Look_Up_Table_3[508] = 17'sb00111111111111111;
  assign Look_Up_Table_3[509] = 17'sb00111111111111111;
  assign Look_Up_Table_3[510] = 17'sb01000000000000000;
  assign Look_Up_Table_3[511] = 17'sb01000000000000000;
  assign Look_Up_Table_out1_1 = Look_Up_Table_3[prelookup_idx_1];

  always @(posedge clk)
    begin : Unit_Delay_process
      if (enb) begin
        Unit_Delay_out1_1 <= Look_Up_Table_out1_1;
      end
    end

  assign Negate_cast = {Unit_Delay_out1_1[16], Unit_Delay_out1_1};
  assign Negate_cast_1 =  - (Negate_cast);
  assign Negate_out1_1 = Negate_cast_1[16:0];

  assign Cosine = (RAMDelayBalance_out1_1 == 8'b00000000 ? Negate_out1_1 :
              Unit_Delay_out1_1);

  assign y = Cosine;

endmodule  // Cosine_HDL_Optimized_block1

