// -------------------------------------------------------------
// 
// File Name: C:\Users\Aweso\hdlsrc\aquapack_9_5\aquapack_9_5\Distance_Finder5.v
// Created: 2026-09-14 17:02:35
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Distance_Finder5
// Source Path: aquapack_9_5/Parallel Beamformer/Distance Finder5
// Hierarchy Level: 1
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Distance_Finder5
          (clk,
           reset,
           enb,
           Theta,
           X_Position,
           Y_Position,
           Distance);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] Theta;  // sfix16_En12
  input   signed [16:0] X_Position;  // sfix17_En15
  input   signed [16:0] Y_Position;  // sfix17_En15
  output  signed [17:0] Distance;  // sfix18_En15


  wire signed [16:0] Cosine_HDL_Optimized_x;  // sfix17_En15
  wire signed [16:0] Cosine_HDL_Optimized_y;  // sfix17_En15
  reg signed [16:0] Delay4_out1;  // sfix17_En15
  reg signed [16:0] Delay4_out1_1;  // sfix17_En15
  reg signed [16:0] Delay11_out1;  // sfix17_En15
  reg signed [16:0] Delay11_out1_1;  // sfix17_En15
  wire signed [33:0] Product5_mul_temp;  // sfix34_En30
  wire signed [16:0] Product5_out1;  // sfix17_En15
  reg signed [16:0] Product5_out1_1;  // sfix17_En15
  reg signed [16:0] cos;  // sfix17_En15
  reg signed [16:0] cos_1;  // sfix17_En15
  reg signed [16:0] Delay_out1;  // sfix17_En15
  reg signed [16:0] Delay_out1_1;  // sfix17_En15
  wire signed [33:0] Product2_mul_temp;  // sfix34_En30
  wire signed [16:0] Cos_dist;  // sfix17_En15
  reg signed [16:0] Cos_dist_1;  // sfix17_En15
  wire signed [17:0] Add_add_cast;  // sfix18_En15
  wire signed [17:0] Add_add_cast_1;  // sfix18_En15
  wire signed [17:0] Distance_1;  // sfix18_En15


  Cosine_HDL_Optimized_block4 u_Cosine_HDL_Optimized (.clk(clk),
                                                      .reset(reset),
                                                      .enb(enb),
                                                      .u(Theta),  // sfix16_En12
                                                      .x(Cosine_HDL_Optimized_x),  // sfix17_En15
                                                      .y(Cosine_HDL_Optimized_y)  // sfix17_En15
                                                      );

  always @(posedge clk)
    begin : Delay4_process
      if (reset == 1'b0) begin
        Delay4_out1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= Cosine_HDL_Optimized_x;
        end
      end
    end

  always @(posedge clk)
    begin : HwModeRegister2_process
      if (reset == 1'b0) begin
        Delay4_out1_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Delay4_out1_1 <= Delay4_out1;
        end
      end
    end

  always @(posedge clk)
    begin : Delay11_process
      if (reset == 1'b0) begin
        Delay11_out1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Delay11_out1 <= Y_Position;
        end
      end
    end

  always @(posedge clk)
    begin : HwModeRegister3_process
      if (reset == 1'b0) begin
        Delay11_out1_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Delay11_out1_1 <= Delay11_out1;
        end
      end
    end

  assign Product5_mul_temp = Delay4_out1_1 * Delay11_out1_1;
  assign Product5_out1 = Product5_mul_temp[31:15];

  always @(posedge clk)
    begin : PipelineRegister1_process
      if (reset == 1'b0) begin
        Product5_out1_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Product5_out1_1 <= Product5_out1;
        end
      end
    end

  always @(posedge clk)
    begin : Delay10_process
      if (reset == 1'b0) begin
        cos <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          cos <= Cosine_HDL_Optimized_y;
        end
      end
    end

  always @(posedge clk)
    begin : HwModeRegister_process
      if (reset == 1'b0) begin
        cos_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          cos_1 <= cos;
        end
      end
    end

  always @(posedge clk)
    begin : Delay_process
      if (reset == 1'b0) begin
        Delay_out1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= X_Position;
        end
      end
    end

  always @(posedge clk)
    begin : HwModeRegister1_process
      if (reset == 1'b0) begin
        Delay_out1_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1_1 <= Delay_out1;
        end
      end
    end

  assign Product2_mul_temp = cos_1 * Delay_out1_1;
  assign Cos_dist = Product2_mul_temp[31:15];

  always @(posedge clk)
    begin : PipelineRegister_process
      if (reset == 1'b0) begin
        Cos_dist_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Cos_dist_1 <= Cos_dist;
        end
      end
    end

  assign Add_add_cast = {Product5_out1_1[16], Product5_out1_1};
  assign Add_add_cast_1 = {Cos_dist_1[16], Cos_dist_1};
  assign Distance_1 = Add_add_cast + Add_add_cast_1;

  assign Distance = Distance_1;

endmodule  // Distance_Finder5

