// -------------------------------------------------------------
// 
// File Name: C:\Users\Aweso\hdlsrc\aquapack_9_5\aquapack_9_5\Parallel_Beamformer.v
// Created: 2026-09-14 17:02:35
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.244141
// Target subsystem base rate: 0.244141
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.244141
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Array_Value_re_0              ce_out        0.244141
// Array_Value_re_1              ce_out        0.244141
// Array_Value_re_2              ce_out        0.244141
// Array_Value_re_3              ce_out        0.244141
// Array_Value_re_4              ce_out        0.244141
// Array_Value_re_5              ce_out        0.244141
// Array_Value_im_0              ce_out        0.244141
// Array_Value_im_1              ce_out        0.244141
// Array_Value_im_2              ce_out        0.244141
// Array_Value_im_3              ce_out        0.244141
// Array_Value_im_4              ce_out        0.244141
// Array_Value_im_5              ce_out        0.244141
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Parallel_Beamformer
// Source Path: aquapack_9_5/Parallel Beamformer
// Hierarchy Level: 0
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Parallel_Beamformer
          (clk,
           reset,
           clk_enable,
           Theta,
           Frequency,
           ce_out,
           Array_Value_re_0,
           Array_Value_re_1,
           Array_Value_re_2,
           Array_Value_re_3,
           Array_Value_re_4,
           Array_Value_re_5,
           Array_Value_im_0,
           Array_Value_im_1,
           Array_Value_im_2,
           Array_Value_im_3,
           Array_Value_im_4,
           Array_Value_im_5);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] Theta;  // sfix16_En12
  input   [7:0] Frequency;  // uint8
  output  ce_out;
  output  signed [16:0] Array_Value_re_0;  // sfix17_En15
  output  signed [16:0] Array_Value_re_1;  // sfix17_En15
  output  signed [16:0] Array_Value_re_2;  // sfix17_En15
  output  signed [16:0] Array_Value_re_3;  // sfix17_En15
  output  signed [16:0] Array_Value_re_4;  // sfix17_En15
  output  signed [16:0] Array_Value_re_5;  // sfix17_En15
  output  signed [16:0] Array_Value_im_0;  // sfix17_En15
  output  signed [16:0] Array_Value_im_1;  // sfix17_En15
  output  signed [16:0] Array_Value_im_2;  // sfix17_En15
  output  signed [16:0] Array_Value_im_3;  // sfix17_En15
  output  signed [16:0] Array_Value_im_4;  // sfix17_En15
  output  signed [16:0] Array_Value_im_5;  // sfix17_En15


  wire signed [16:0] x_pos_25k_out1 [0:5];  // sfix17_En15 [6]
  wire signed [16:0] x_pos_30k_out1 [0:5];  // sfix17_En15 [6]
  wire signed [16:0] x_pos_35k_out1 [0:5];  // sfix17_En15 [6]
  wire signed [16:0] x_pos_40k_out1 [0:5];  // sfix17_En15 [6]
  reg signed [16:0] Multiport_Switch_out1 [0:5];  // sfix17_En15 [6]
  wire signed [16:0] y_pos_25k_out1 [0:5];  // sfix17_En15 [6]
  wire signed [16:0] y_pos_30k_out1 [0:5];  // sfix17_En15 [6]
  wire signed [16:0] y_pos_35k_out1 [0:5];  // sfix17_En15 [6]
  wire signed [16:0] y_pos_40k_out1 [0:5];  // sfix17_En15 [6]
  reg signed [16:0] Multiport_Switch1_out1 [0:5];  // sfix17_En15 [6]
  wire signed [17:0] Distance_Finder1_Distance;  // sfix18_En15
  wire signed [15:0] Converted_Distance;  // sfix16_En13
  wire signed [16:0] Cosine_HDL_Optimized_x_re;  // sfix17_En15
  wire signed [16:0] Cosine_HDL_Optimized_x_im;  // sfix17_En15
  wire signed [17:0] Distance_Finder2_Distance;  // sfix18_En15
  wire signed [15:0] Converted_Distance_1;  // sfix16_En13
  wire signed [16:0] Cosine_HDL_Optimized1_x_re;  // sfix17_En15
  wire signed [16:0] Cosine_HDL_Optimized1_x_im;  // sfix17_En15
  wire signed [17:0] Distance_Finder3_Distance;  // sfix18_En15
  wire signed [15:0] Converted_Distance_2;  // sfix16_En13
  wire signed [16:0] Cosine_HDL_Optimized2_x_re;  // sfix17_En15
  wire signed [16:0] Cosine_HDL_Optimized2_x_im;  // sfix17_En15
  wire signed [17:0] Distance_Finder4_Distance;  // sfix18_En15
  wire signed [15:0] Converted_Distance_3;  // sfix16_En13
  wire signed [16:0] Cosine_HDL_Optimized3_x_re;  // sfix17_En15
  wire signed [16:0] Cosine_HDL_Optimized3_x_im;  // sfix17_En15
  wire signed [17:0] Distance_Finder5_Distance;  // sfix18_En15
  wire signed [15:0] Converted_Distance_4;  // sfix16_En13
  wire signed [16:0] Cosine_HDL_Optimized4_x_re;  // sfix17_En15
  wire signed [16:0] Cosine_HDL_Optimized4_x_im;  // sfix17_En15
  wire signed [17:0] Distance_Finder6_Distance;  // sfix18_En15
  wire signed [15:0] Converted_Distance_5;  // sfix16_En13
  wire signed [16:0] Cosine_HDL_Optimized5_x_re;  // sfix17_En15
  wire signed [16:0] Cosine_HDL_Optimized5_x_im;  // sfix17_En15
  wire signed [16:0] ParallelArrayFactor_re [0:5];  // sfix17_En15 [6]
  wire signed [16:0] ParallelArrayFactor_im [0:5];  // sfix17_En15 [6]
  reg signed [31:0] Multiport_Switch_t_0_0;  // int32
  reg signed [31:0] Multiport_Switch_t_1;  // int32
  reg signed [31:0] Multiport_Switch_t_2_0;  // int32
  reg signed [31:0] Multiport_Switch_t_3;  // int32
  reg signed [31:0] Multiport_Switch1_t_0_0;  // int32
  reg signed [31:0] Multiport_Switch1_t_1;  // int32
  reg signed [31:0] Multiport_Switch1_t_2_0;  // int32
  reg signed [31:0] Multiport_Switch1_t_3;  // int32


  assign x_pos_25k_out1[0] = 17'sb00011011011101011;
  assign x_pos_25k_out1[1] = 17'sb00001000011111001;
  assign x_pos_25k_out1[2] = 17'sb11101001110010010;
  assign x_pos_25k_out1[3] = 17'sb11101001110010010;
  assign x_pos_25k_out1[4] = 17'sb00001000011111001;
  assign x_pos_25k_out1[5] = 17'sb00000000000000000;

  assign x_pos_30k_out1[0] = 17'sb00100000111100111;
  assign x_pos_30k_out1[1] = 17'sb00001010001011101;
  assign x_pos_30k_out1[2] = 17'sb11100101010101111;
  assign x_pos_30k_out1[3] = 17'sb11100101010101111;
  assign x_pos_30k_out1[4] = 17'sb00001010001011101;
  assign x_pos_30k_out1[5] = 17'sb00000000000000000;

  assign x_pos_35k_out1[0] = 17'sb00100110011100011;
  assign x_pos_35k_out1[1] = 17'sb00001011111000010;
  assign x_pos_35k_out1[2] = 17'sb11100000111001100;
  assign x_pos_35k_out1[3] = 17'sb11100000111001100;
  assign x_pos_35k_out1[4] = 17'sb00001011111000010;
  assign x_pos_35k_out1[5] = 17'sb00000000000000000;

  assign x_pos_40k_out1[0] = 17'sb00101011111011111;
  assign x_pos_40k_out1[1] = 17'sb00001101100100111;
  assign x_pos_40k_out1[2] = 17'sb11011100011101001;
  assign x_pos_40k_out1[3] = 17'sb11011100011101001;
  assign x_pos_40k_out1[4] = 17'sb00001101100100111;
  assign x_pos_40k_out1[5] = 17'sb00000000000000000;

  always @* begin
    if (Frequency == 8'b00000000) begin
      for(Multiport_Switch_t_0_0 = 32'sd0; Multiport_Switch_t_0_0 <= 32'sd5; Multiport_Switch_t_0_0 = Multiport_Switch_t_0_0 + 32'sd1) begin
        Multiport_Switch_out1[Multiport_Switch_t_0_0] = x_pos_25k_out1[Multiport_Switch_t_0_0];
      end
    end
    else if (Frequency == 8'b00000001) begin
      for(Multiport_Switch_t_1 = 32'sd0; Multiport_Switch_t_1 <= 32'sd5; Multiport_Switch_t_1 = Multiport_Switch_t_1 + 32'sd1) begin
        Multiport_Switch_out1[Multiport_Switch_t_1] = x_pos_30k_out1[Multiport_Switch_t_1];
      end
    end
    else if (Frequency == 8'b00000010) begin
      for(Multiport_Switch_t_3 = 32'sd0; Multiport_Switch_t_3 <= 32'sd5; Multiport_Switch_t_3 = Multiport_Switch_t_3 + 32'sd1) begin
        Multiport_Switch_out1[Multiport_Switch_t_3] = x_pos_35k_out1[Multiport_Switch_t_3];
      end
    end
    else begin
      for(Multiport_Switch_t_2_0 = 32'sd0; Multiport_Switch_t_2_0 <= 32'sd5; Multiport_Switch_t_2_0 = Multiport_Switch_t_2_0 + 32'sd1) begin
        Multiport_Switch_out1[Multiport_Switch_t_2_0] = x_pos_40k_out1[Multiport_Switch_t_2_0];
      end
    end
  end

  assign y_pos_25k_out1[0] = 17'sb00000000000000000;
  assign y_pos_25k_out1[1] = 17'sb00011010000111011;
  assign y_pos_25k_out1[2] = 17'sb00010000001001000;
  assign y_pos_25k_out1[3] = 17'sb11101111110111000;
  assign y_pos_25k_out1[4] = 17'sb11100101111000101;
  assign y_pos_25k_out1[5] = 17'sb00000000000000000;

  assign y_pos_30k_out1[0] = 17'sb00000000000000000;
  assign y_pos_30k_out1[1] = 17'sb00011111010101101;
  assign y_pos_30k_out1[2] = 17'sb00010011010111101;
  assign y_pos_30k_out1[3] = 17'sb11101100101000011;
  assign y_pos_30k_out1[4] = 17'sb11100000101010011;
  assign y_pos_30k_out1[5] = 17'sb00000000000000000;

  assign y_pos_35k_out1[0] = 17'sb00000000000000000;
  assign y_pos_35k_out1[1] = 17'sb00100100100100000;
  assign y_pos_35k_out1[2] = 17'sb00010110100110001;
  assign y_pos_35k_out1[3] = 17'sb11101001011001111;
  assign y_pos_35k_out1[4] = 17'sb11011011011100000;
  assign y_pos_35k_out1[5] = 17'sb00000000000000000;

  assign y_pos_40k_out1[0] = 17'sb00000000000000000;
  assign y_pos_40k_out1[1] = 17'sb00101001110010010;
  assign y_pos_40k_out1[2] = 17'sb00011001110100110;
  assign y_pos_40k_out1[3] = 17'sb11100110001011010;
  assign y_pos_40k_out1[4] = 17'sb11010110001101110;
  assign y_pos_40k_out1[5] = 17'sb00000000000000000;

  always @* begin
    if (Frequency == 8'b00000000) begin
      for(Multiport_Switch1_t_0_0 = 32'sd0; Multiport_Switch1_t_0_0 <= 32'sd5; Multiport_Switch1_t_0_0 = Multiport_Switch1_t_0_0 + 32'sd1) begin
        Multiport_Switch1_out1[Multiport_Switch1_t_0_0] = y_pos_25k_out1[Multiport_Switch1_t_0_0];
      end
    end
    else if (Frequency == 8'b00000001) begin
      for(Multiport_Switch1_t_1 = 32'sd0; Multiport_Switch1_t_1 <= 32'sd5; Multiport_Switch1_t_1 = Multiport_Switch1_t_1 + 32'sd1) begin
        Multiport_Switch1_out1[Multiport_Switch1_t_1] = y_pos_30k_out1[Multiport_Switch1_t_1];
      end
    end
    else if (Frequency == 8'b00000010) begin
      for(Multiport_Switch1_t_3 = 32'sd0; Multiport_Switch1_t_3 <= 32'sd5; Multiport_Switch1_t_3 = Multiport_Switch1_t_3 + 32'sd1) begin
        Multiport_Switch1_out1[Multiport_Switch1_t_3] = y_pos_35k_out1[Multiport_Switch1_t_3];
      end
    end
    else begin
      for(Multiport_Switch1_t_2_0 = 32'sd0; Multiport_Switch1_t_2_0 <= 32'sd5; Multiport_Switch1_t_2_0 = Multiport_Switch1_t_2_0 + 32'sd1) begin
        Multiport_Switch1_out1[Multiport_Switch1_t_2_0] = y_pos_40k_out1[Multiport_Switch1_t_2_0];
      end
    end
  end

  Distance_Finder1 u_Distance_Finder1 (.clk(clk),
                                       .reset(reset),
                                       .enb(clk_enable),
                                       .Theta(Theta),  // sfix16_En12
                                       .X_Position(Multiport_Switch_out1[0]),  // sfix17_En15
                                       .Y_Position(Multiport_Switch1_out1[0]),  // sfix17_En15
                                       .Distance(Distance_Finder1_Distance)  // sfix18_En15
                                       );

  assign Converted_Distance = Distance_Finder1_Distance[17:2];

  Cosine_HDL_Optimized u_Cosine_HDL_Optimized (.clk(clk),
                                               .reset(reset),
                                               .enb(clk_enable),
                                               .u(Converted_Distance),  // sfix16_En13
                                               .x_re(Cosine_HDL_Optimized_x_re),  // sfix17_En15
                                               .x_im(Cosine_HDL_Optimized_x_im)  // sfix17_En15
                                               );

  Distance_Finder2 u_Distance_Finder2 (.clk(clk),
                                       .reset(reset),
                                       .enb(clk_enable),
                                       .Theta(Theta),  // sfix16_En12
                                       .X_Position(Multiport_Switch_out1[1]),  // sfix17_En15
                                       .Y_Position(Multiport_Switch1_out1[1]),  // sfix17_En15
                                       .Distance(Distance_Finder2_Distance)  // sfix18_En15
                                       );

  assign Converted_Distance_1 = Distance_Finder2_Distance[17:2];

  Cosine_HDL_Optimized1 u_Cosine_HDL_Optimized1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .u(Converted_Distance_1),  // sfix16_En13
                                                 .x_re(Cosine_HDL_Optimized1_x_re),  // sfix17_En15
                                                 .x_im(Cosine_HDL_Optimized1_x_im)  // sfix17_En15
                                                 );

  Distance_Finder3 u_Distance_Finder3 (.clk(clk),
                                       .reset(reset),
                                       .enb(clk_enable),
                                       .Theta(Theta),  // sfix16_En12
                                       .X_Position(Multiport_Switch_out1[2]),  // sfix17_En15
                                       .Y_Position(Multiport_Switch1_out1[2]),  // sfix17_En15
                                       .Distance(Distance_Finder3_Distance)  // sfix18_En15
                                       );

  assign Converted_Distance_2 = Distance_Finder3_Distance[17:2];

  Cosine_HDL_Optimized2 u_Cosine_HDL_Optimized2 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .u(Converted_Distance_2),  // sfix16_En13
                                                 .x_re(Cosine_HDL_Optimized2_x_re),  // sfix17_En15
                                                 .x_im(Cosine_HDL_Optimized2_x_im)  // sfix17_En15
                                                 );

  Distance_Finder4 u_Distance_Finder4 (.clk(clk),
                                       .reset(reset),
                                       .enb(clk_enable),
                                       .Theta(Theta),  // sfix16_En12
                                       .X_Position(Multiport_Switch_out1[3]),  // sfix17_En15
                                       .Y_Position(Multiport_Switch1_out1[3]),  // sfix17_En15
                                       .Distance(Distance_Finder4_Distance)  // sfix18_En15
                                       );

  assign Converted_Distance_3 = Distance_Finder4_Distance[17:2];

  Cosine_HDL_Optimized3 u_Cosine_HDL_Optimized3 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .u(Converted_Distance_3),  // sfix16_En13
                                                 .x_re(Cosine_HDL_Optimized3_x_re),  // sfix17_En15
                                                 .x_im(Cosine_HDL_Optimized3_x_im)  // sfix17_En15
                                                 );

  Distance_Finder5 u_Distance_Finder5 (.clk(clk),
                                       .reset(reset),
                                       .enb(clk_enable),
                                       .Theta(Theta),  // sfix16_En12
                                       .X_Position(Multiport_Switch_out1[4]),  // sfix17_En15
                                       .Y_Position(Multiport_Switch1_out1[4]),  // sfix17_En15
                                       .Distance(Distance_Finder5_Distance)  // sfix18_En15
                                       );

  assign Converted_Distance_4 = Distance_Finder5_Distance[17:2];

  Cosine_HDL_Optimized4 u_Cosine_HDL_Optimized4 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .u(Converted_Distance_4),  // sfix16_En13
                                                 .x_re(Cosine_HDL_Optimized4_x_re),  // sfix17_En15
                                                 .x_im(Cosine_HDL_Optimized4_x_im)  // sfix17_En15
                                                 );

  Distance_Finder6 u_Distance_Finder6 (.clk(clk),
                                       .reset(reset),
                                       .enb(clk_enable),
                                       .Theta(Theta),  // sfix16_En12
                                       .X_Position(Multiport_Switch_out1[5]),  // sfix17_En15
                                       .Y_Position(Multiport_Switch1_out1[5]),  // sfix17_En15
                                       .Distance(Distance_Finder6_Distance)  // sfix18_En15
                                       );

  assign Converted_Distance_5 = Distance_Finder6_Distance[17:2];

  Cosine_HDL_Optimized5 u_Cosine_HDL_Optimized5 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .u(Converted_Distance_5),  // sfix16_En13
                                                 .x_re(Cosine_HDL_Optimized5_x_re),  // sfix17_En15
                                                 .x_im(Cosine_HDL_Optimized5_x_im)  // sfix17_En15
                                                 );

  assign ParallelArrayFactor_re[0] = Cosine_HDL_Optimized_x_re;
  assign ParallelArrayFactor_re[1] = Cosine_HDL_Optimized1_x_re;
  assign ParallelArrayFactor_re[2] = Cosine_HDL_Optimized2_x_re;
  assign ParallelArrayFactor_re[3] = Cosine_HDL_Optimized3_x_re;
  assign ParallelArrayFactor_re[4] = Cosine_HDL_Optimized4_x_re;
  assign ParallelArrayFactor_re[5] = Cosine_HDL_Optimized5_x_re;

  assign Array_Value_re_0 = ParallelArrayFactor_re[0];

  assign Array_Value_re_1 = ParallelArrayFactor_re[1];

  assign Array_Value_re_2 = ParallelArrayFactor_re[2];

  assign Array_Value_re_3 = ParallelArrayFactor_re[3];

  assign Array_Value_re_4 = ParallelArrayFactor_re[4];

  assign Array_Value_re_5 = ParallelArrayFactor_re[5];

  assign ParallelArrayFactor_im[0] = Cosine_HDL_Optimized_x_im;
  assign ParallelArrayFactor_im[1] = Cosine_HDL_Optimized1_x_im;
  assign ParallelArrayFactor_im[2] = Cosine_HDL_Optimized2_x_im;
  assign ParallelArrayFactor_im[3] = Cosine_HDL_Optimized3_x_im;
  assign ParallelArrayFactor_im[4] = Cosine_HDL_Optimized4_x_im;
  assign ParallelArrayFactor_im[5] = Cosine_HDL_Optimized5_x_im;

  assign Array_Value_im_0 = ParallelArrayFactor_im[0];

  assign Array_Value_im_1 = ParallelArrayFactor_im[1];

  assign Array_Value_im_2 = ParallelArrayFactor_im[2];

  assign Array_Value_im_3 = ParallelArrayFactor_im[3];

  assign Array_Value_im_4 = ParallelArrayFactor_im[4];

  assign Array_Value_im_5 = ParallelArrayFactor_im[5];

  assign ce_out = clk_enable;

endmodule  // Parallel_Beamformer

