// -------------------------------------------------------------
// 
// File Name: C:\Users\Aweso\Verilog\Aquapack\bartlett\sim\bartlett_datapath\codegen\hilbert_fir_filter_1027\hdlsrc\dsphdl_FIRFilter.v
// Created: 2025-10-27 17:59:07
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dsphdl_FIRFilter
// Source Path: hilbert_fir_filter_1027/dsphdl.FIRFilter
// Hierarchy Level: 1
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dsphdl_FIRFilter
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           syncReset,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  input   syncReset;
  output  signed [31:0] dataOut;  // sfix32_En29
  output  validOut;




  Filter u_FilterBank (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .dataIn(dataIn),  // sfix16_En15
                       .validIn(validIn),
                       .syncReset(syncReset),
                       .dataOut(dataOut),  // sfix32_En29
                       .validOut(validOut)
                       );

endmodule  // dsphdl_FIRFilter

