// -------------------------------------------------------------
// 
// File Name: C:\Users\Aweso\MATLAB\codegen\hilbert_fir_filter\hdlsrc\FilterCoef.v
// Created: 2025-10-08 10:20:34
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterCoef
// Source Path: hilbert_fir_filter/dsphdl.FIRFilter/Filter/FilterCoef
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterCoef
          (validIn,
           syncReset,
           CoefOut_0,
           CoefOut_1,
           CoefOut_2,
           CoefOut_3,
           CoefOut_4,
           CoefOut_5,
           CoefOut_6,
           CoefOut_7,
           CoefOut_8,
           CoefOut_9,
           CoefOut_10);


  input   validIn;
  input   syncReset;
  output  signed [15:0] CoefOut_0;  // sfix16_En15
  output  signed [15:0] CoefOut_1;  // sfix16_En15
  output  signed [15:0] CoefOut_2;  // sfix16_En15
  output  signed [15:0] CoefOut_3;  // sfix16_En15
  output  signed [15:0] CoefOut_4;  // sfix16_En15
  output  signed [15:0] CoefOut_5;  // sfix16_En15
  output  signed [15:0] CoefOut_6;  // sfix16_En15
  output  signed [15:0] CoefOut_7;  // sfix16_En15
  output  signed [15:0] CoefOut_8;  // sfix16_En15
  output  signed [15:0] CoefOut_9;  // sfix16_En15
  output  signed [15:0] CoefOut_10;  // sfix16_En15


  wire signed [15:0] CoefData;  // sfix16_En15
  wire signed [15:0] CoefData_1;  // sfix16_En15
  wire signed [15:0] CoefData_2;  // sfix16_En15
  wire signed [15:0] CoefData_3;  // sfix16_En15
  wire signed [15:0] CoefData_4;  // sfix16_En15
  wire signed [15:0] CoefData_5;  // sfix16_En15
  wire signed [15:0] CoefData_6;  // sfix16_En15
  wire signed [15:0] CoefData_7;  // sfix16_En15
  wire signed [15:0] CoefData_8;  // sfix16_En15
  wire signed [15:0] CoefData_9;  // sfix16_En15
  wire signed [15:0] CoefData_10;  // sfix16_En15


  // CoefReg_1
  assign CoefData = 16'sb1110001110010011;

  assign CoefOut_0 = CoefData;

  // CoefReg_2
  assign CoefData_1 = 16'sb0000000000000000;

  assign CoefOut_1 = CoefData_1;

  // CoefReg_3
  assign CoefData_2 = 16'sb1110010101111111;

  assign CoefOut_2 = CoefData_2;

  // CoefReg_4
  assign CoefData_3 = 16'sb0000000000000000;

  assign CoefOut_3 = CoefData_3;

  // CoefReg_5
  assign CoefData_4 = 16'sb1010111011000011;

  assign CoefOut_4 = CoefData_4;

  // CoefReg_6
  assign CoefData_5 = 16'sb0000000000000000;

  assign CoefOut_5 = CoefData_5;

  // CoefReg_7
  assign CoefData_6 = 16'sb0101000100111101;

  assign CoefOut_6 = CoefData_6;

  // CoefReg_8
  assign CoefData_7 = 16'sb0000000000000000;

  assign CoefOut_7 = CoefData_7;

  // CoefReg_9
  assign CoefData_8 = 16'sb0001101010000001;

  assign CoefOut_8 = CoefData_8;

  // CoefReg_10
  assign CoefData_9 = 16'sb0000000000000000;

  assign CoefOut_9 = CoefData_9;

  // CoefReg_11
  assign CoefData_10 = 16'sb0001110001101101;

  assign CoefOut_10 = CoefData_10;

endmodule  // FilterCoef

