// -------------------------------------------------------------
// 
// File Name: C:\Users\Aweso\MATLAB\codegen\hilbert_fir_filter\hdlsrc\FilterTapSystolicWvldInC0.v
// Created: 2025-10-08 16:40:52
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapSystolicWvldInC0
// Source Path: hilbert_fir_filter/dsphdl.FIRFilter/Filter/subFilter/FilterTapSystolicWvldInC0
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterTapSystolicWvldInC0
          (clk,
           reset,
           enb,
           dinReg2_0_re,
           addin,
           dinRegVld,
           syncReset,
           dinDly2,
           tapout,
           tapoutVld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dinReg2_0_re;  // sfix16_En15
  input   signed [47:0] addin;  // sfix48_En29
  input   dinRegVld;
  input   syncReset;
  output  signed [15:0] dinDly2;  // sfix16_En15
  output  signed [47:0] tapout;  // sfix48_En29
  output  tapoutVld;


  reg signed [15:0] fTap_din1_reg1;  // sfix16
  reg signed [15:0] fTap_din1_reg2;  // sfix16
  reg signed [47:0] fTap_addout_reg;  // sfix48
  reg signed [15:0] fTap_din1_reg1_next;  // sfix16_En15
  reg signed [15:0] fTap_din1_reg2_next;  // sfix16_En15
  reg signed [47:0] fTap_addout_reg_next;  // sfix48_En29
  reg signed [15:0] dinDly2_1;  // sfix16_En15
  reg signed [47:0] tapout_1;  // sfix48_En29
  reg  [3:0] intdelay_reg;  // ufix1 [4]

  initial begin
    fTap_din1_reg1 = 16'sb0000000000000000;
    fTap_din1_reg2 = 16'sb0000000000000000;
    fTap_addout_reg = 48'sh000000000000;
  end

  // FilterTapSystolicWvldInC0
  always @(posedge clk)
    begin : fTap_process
      if (enb) begin
        if (syncReset == 1'b1) begin
          fTap_din1_reg1 <= 16'sb0000000000000000;
          fTap_din1_reg2 <= 16'sb0000000000000000;
          fTap_addout_reg <= 48'sh000000000000;
        end
        else begin
          fTap_din1_reg1 <= fTap_din1_reg1_next;
          fTap_din1_reg2 <= fTap_din1_reg2_next;
          fTap_addout_reg <= fTap_addout_reg_next;
        end
      end
    end

  always @(addin, dinReg2_0_re, dinRegVld, fTap_addout_reg, fTap_din1_reg1,
       fTap_din1_reg2) begin
    fTap_din1_reg1_next = fTap_din1_reg1;
    fTap_din1_reg2_next = fTap_din1_reg2;
    fTap_addout_reg_next = fTap_addout_reg;
    if (dinRegVld) begin
      fTap_addout_reg_next = addin;
    end
    if (dinRegVld) begin
      fTap_din1_reg2_next = fTap_din1_reg1;
      fTap_din1_reg1_next = dinReg2_0_re;
    end
    dinDly2_1 = fTap_din1_reg2;
    tapout_1 = fTap_addout_reg;
  end

  always @(posedge clk or negedge reset)
    begin : intdelay_process
      if (reset == 1'b0) begin
        intdelay_reg <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg <= {4{1'b0}};
          end
          else begin
            intdelay_reg[0] <= dinRegVld;
            intdelay_reg[32'sd3:32'sd1] <= intdelay_reg[32'sd2:32'sd0];
          end
        end
      end
    end

  assign tapoutVld = intdelay_reg[3];

  assign dinDly2 = dinDly2_1;

  assign tapout = tapout_1;

endmodule  // FilterTapSystolicWvldInC0

