// -------------------------------------------------------------
// 
// File Name: C:\Users\Aweso\MATLAB\codegen\hilbert_fir_filter\hdlsrc\Filter.v
// Created: 2025-10-08 16:40:52
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Filter
// Source Path: hilbert_fir_filter/dsphdl.FIRFilter/Filter
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Filter
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           syncReset,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  input   syncReset;
  output  signed [15:0] dataOut;  // sfix16_En13
  output  validOut;


  reg  dinRegVld;
  reg signed [15:0] dinReg_0_re;  // sfix16_En15
  reg signed [15:0] dinReg2_0_re;  // sfix16_En15
  wire signed [15:0] CoefOut_0;  // sfix16_En14
  wire signed [15:0] CoefOut_1;  // sfix16_En14
  wire signed [15:0] CoefOut_2;  // sfix16_En14
  wire signed [15:0] CoefOut_3;  // sfix16_En14
  wire signed [15:0] CoefOut_4;  // sfix16_En14
  wire signed [15:0] CoefOut_5;  // sfix16_En14
  wire signed [15:0] CoefOut_6;  // sfix16_En14
  wire signed [15:0] CoefOut_7;  // sfix16_En14
  wire signed [15:0] CoefOut_8;  // sfix16_En14
  wire signed [15:0] CoefOut_9;  // sfix16_En14
  wire signed [15:0] CoefOut_10;  // sfix16_En14
  reg  dinReg2Vld;
  wire signed [15:0] dout_1_re;  // sfix16_En13
  wire doutVld;


  always @(posedge clk or negedge reset)
    begin : intdelay_process
      if (reset == 1'b0) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : intdelay_1_process
      if (reset == 1'b0) begin
        dinReg_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn;
            end
          end
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : intdelay_2_process
      if (reset == 1'b0) begin
        dinReg2_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_0_re;
            end
          end
        end
      end
    end

  FilterCoef u_CoefTable_1 (.validIn(validIn),
                            .syncReset(syncReset),
                            .CoefOut_0(CoefOut_0),  // sfix16_En14
                            .CoefOut_1(CoefOut_1),  // sfix16_En14
                            .CoefOut_2(CoefOut_2),  // sfix16_En14
                            .CoefOut_3(CoefOut_3),  // sfix16_En14
                            .CoefOut_4(CoefOut_4),  // sfix16_En14
                            .CoefOut_5(CoefOut_5),  // sfix16_En14
                            .CoefOut_6(CoefOut_6),  // sfix16_En14
                            .CoefOut_7(CoefOut_7),  // sfix16_En14
                            .CoefOut_8(CoefOut_8),  // sfix16_En14
                            .CoefOut_9(CoefOut_9),  // sfix16_En14
                            .CoefOut_10(CoefOut_10)  // sfix16_En14
                            );

  always @(posedge clk or negedge reset)
    begin : intdelay_3_process
      if (reset == 1'b0) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end

  subFilter u_subFilter_1_re (.clk(clk),
                              .reset(reset),
                              .enb(enb),
                              .dinReg2_0_re(dinReg2_0_re),  // sfix16_En15
                              .coefIn_0(CoefOut_0),  // sfix16_En14
                              .coefIn_1(CoefOut_1),  // sfix16_En14
                              .coefIn_2(CoefOut_2),  // sfix16_En14
                              .coefIn_3(CoefOut_3),  // sfix16_En14
                              .coefIn_4(CoefOut_4),  // sfix16_En14
                              .coefIn_5(CoefOut_5),  // sfix16_En14
                              .coefIn_6(CoefOut_6),  // sfix16_En14
                              .coefIn_7(CoefOut_7),  // sfix16_En14
                              .coefIn_8(CoefOut_8),  // sfix16_En14
                              .coefIn_9(CoefOut_9),  // sfix16_En14
                              .coefIn_10(CoefOut_10),  // sfix16_En14
                              .dinRegVld(dinReg2Vld),
                              .syncReset(syncReset),
                              .dout_1_re(dout_1_re),  // sfix16_En13
                              .doutVld(doutVld)
                              );

  assign dataOut = dout_1_re;

  assign validOut = doutVld;

endmodule  // Filter

