// -------------------------------------------------------------
// 
// File Name: C:\Users\Aweso\Verilog\Aquapack\bartlett\sim\bartlett_datapath\codegen\hilbert_fir_filter_1027\hdlsrc\FilterTapSystolicPreAddWvlIn.v
// Created: 2025-10-27 17:59:07
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapSystolicPreAddWvlIn
// Source Path: hilbert_fir_filter_1027/dsphdl.FIRFilter/Filter/subFilter/FilterTapSystolicPreAddWvlIn
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterTapSystolicPreAddWvlIn
          (clk,
           enb,
           dinReg2_0_re,
           dinPreAdd,
           coefIn_0,
           addin,
           dinRegVld,
           syncReset,
           dinDly2,
           tapout);


  input   clk;
  input   enb;
  input   signed [15:0] dinReg2_0_re;  // sfix16_En15
  input   signed [15:0] dinPreAdd;  // sfix16_En15
  input   signed [15:0] coefIn_0;  // sfix16_En14
  input   signed [47:0] addin;  // sfix48_En29
  input   dinRegVld;
  input   syncReset;
  output  signed [15:0] dinDly2;  // sfix16_En15
  output  signed [47:0] tapout;  // sfix48_En29


  reg signed [32:0] fTap_mult_reg;  // sfix33
  reg signed [15:0] fTap_din1_reg1;  // sfix16
  reg signed [15:0] fTap_din1_reg2;  // sfix16
  reg signed [15:0] fTap_din2_reg1;  // sfix16
  reg signed [16:0] fTap_preAdd_reg;  // sfix17
  reg signed [47:0] fTap_addout_reg;  // sfix48
  reg signed [15:0] fTap_coef_reg1;  // sfix16
  reg signed [15:0] fTap_coef_reg2;  // sfix16
  reg signed [32:0] fTap_mult_reg_next;  // sfix33_En29
  reg signed [15:0] fTap_din1_reg1_next;  // sfix16_En15
  reg signed [15:0] fTap_din1_reg2_next;  // sfix16_En15
  reg signed [15:0] fTap_din2_reg1_next;  // sfix16_En15
  reg signed [16:0] fTap_preAdd_reg_next;  // sfix17_En15
  reg signed [47:0] fTap_addout_reg_next;  // sfix48_En29
  reg signed [15:0] fTap_coef_reg1_next;  // sfix16_En14
  reg signed [15:0] fTap_coef_reg2_next;  // sfix16_En14
  reg signed [15:0] dinDly2_1;  // sfix16_En15
  reg signed [47:0] tapout_1;  // sfix48_En29
  reg signed [47:0] fTap_add_cast;  // sfix48_En29
  reg signed [16:0] fTap_sub_cast;  // sfix17_En15
  reg signed [16:0] fTap_sub_cast_0;  // sfix17_En15

  initial begin
    fTap_din1_reg1 = 16'sb0000000000000000;
    fTap_din1_reg2 = 16'sb0000000000000000;
    fTap_din2_reg1 = 16'sb0000000000000000;
    fTap_preAdd_reg = 17'sb00000000000000000;
    fTap_coef_reg1 = 16'sb0000000000000000;
    fTap_coef_reg2 = 16'sb0000000000000000;
    fTap_mult_reg = 33'sh000000000;
    fTap_addout_reg = 48'sh000000000000;
  end

  // FilterTapSystolicPreAddWvldIn
  always @(posedge clk)
    begin : fTap_process
      if (enb) begin
        if (syncReset == 1'b1) begin
          fTap_din1_reg1 <= 16'sb0000000000000000;
          fTap_din1_reg2 <= 16'sb0000000000000000;
          fTap_din2_reg1 <= 16'sb0000000000000000;
          fTap_preAdd_reg <= 17'sb00000000000000000;
          fTap_coef_reg1 <= 16'sb0000000000000000;
          fTap_coef_reg2 <= 16'sb0000000000000000;
          fTap_mult_reg <= 33'sh000000000;
          fTap_addout_reg <= 48'sh000000000000;
        end
        else begin
          fTap_mult_reg <= fTap_mult_reg_next;
          fTap_din1_reg1 <= fTap_din1_reg1_next;
          fTap_din1_reg2 <= fTap_din1_reg2_next;
          fTap_din2_reg1 <= fTap_din2_reg1_next;
          fTap_preAdd_reg <= fTap_preAdd_reg_next;
          fTap_addout_reg <= fTap_addout_reg_next;
          fTap_coef_reg1 <= fTap_coef_reg1_next;
          fTap_coef_reg2 <= fTap_coef_reg2_next;
        end
      end
    end

  always @(addin, coefIn_0, dinPreAdd, dinReg2_0_re, dinRegVld, fTap_addout_reg,
       fTap_coef_reg1, fTap_coef_reg2, fTap_din1_reg1, fTap_din1_reg2,
       fTap_din2_reg1, fTap_mult_reg, fTap_preAdd_reg) begin
    fTap_add_cast = 48'sh000000000000;
    fTap_sub_cast = 17'sb00000000000000000;
    fTap_sub_cast_0 = 17'sb00000000000000000;
    fTap_mult_reg_next = fTap_mult_reg;
    fTap_din1_reg1_next = fTap_din1_reg1;
    fTap_din1_reg2_next = fTap_din1_reg2;
    fTap_din2_reg1_next = fTap_din2_reg1;
    fTap_preAdd_reg_next = fTap_preAdd_reg;
    fTap_addout_reg_next = fTap_addout_reg;
    fTap_coef_reg1_next = fTap_coef_reg1;
    fTap_coef_reg2_next = fTap_coef_reg2;
    if (dinRegVld) begin
      fTap_add_cast = {{15{fTap_mult_reg[32]}}, fTap_mult_reg};
      fTap_addout_reg_next = fTap_add_cast + addin;
      fTap_mult_reg_next = fTap_preAdd_reg * fTap_coef_reg2;
      fTap_sub_cast = {fTap_din1_reg2[15], fTap_din1_reg2};
      fTap_sub_cast_0 = {fTap_din2_reg1[15], fTap_din2_reg1};
      fTap_preAdd_reg_next = fTap_sub_cast - fTap_sub_cast_0;
      fTap_din1_reg2_next = fTap_din1_reg1;
      fTap_din1_reg1_next = dinReg2_0_re;
      fTap_din2_reg1_next = dinPreAdd;
      fTap_coef_reg2_next = fTap_coef_reg1;
      fTap_coef_reg1_next = coefIn_0;
    end
    dinDly2_1 = fTap_din1_reg2;
    tapout_1 = fTap_addout_reg;
  end

  assign dinDly2 = dinDly2_1;

  assign tapout = tapout_1;

endmodule  // FilterTapSystolicPreAddWvlIn

