// -------------------------------------------------------------
// 
// File Name: C:\Users\Aweso\MATLAB\codegen\hilbert_fir_filter\hdlsrc\hilbert_fir_filter.v
// Created: 2025-10-08 10:20:34
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// dataOut                       ce_out        1
// validOut                      ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: hilbert_fir_filter
// Source Path: hilbert_fir_filter
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module hilbert_fir_filter
          (clk,
           reset,
           clk_enable,
           dataIn,
           validIn,
           ce_out,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  ce_out;
  output  signed [32:0] dataOut;  // sfix33_En30
  output  validOut;


  wire signed [32:0] varargout_1;  // sfix33_En30
  wire varargout_2;


  // Generated by HDL IP Designer.
  dsphdl_FIRFilter u_dsphdl_FIRFilter (.clk(clk),
                                       .reset(reset),
                                       .enb(clk_enable),
                                       .dataIn(dataIn),  // sfix16_En15
                                       .validIn(validIn),
                                       .dataOut(varargout_1),  // sfix33_En30
                                       .validOut(varargout_2)
                                       );

  assign dataOut = varargout_1;

  assign validOut = varargout_2;

  assign ce_out = clk_enable;

endmodule  // hilbert_fir_filter

