// -------------------------------------------------------------
// 
// File Name: C:\Users\Aweso\MATLAB\codegen\hilbert_fir_filter\hdlsrc\subFilter.v
// Created: 2025-10-08 10:20:34
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: subFilter
// Source Path: hilbert_fir_filter/dsphdl.FIRFilter/Filter/subFilter
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module subFilter
          (clk,
           reset,
           enb,
           dinReg2_0_re,
           coefIn_0,
           coefIn_1,
           coefIn_2,
           coefIn_3,
           coefIn_4,
           coefIn_5,
           coefIn_6,
           coefIn_7,
           coefIn_8,
           coefIn_9,
           coefIn_10,
           dinRegVld,
           syncReset,
           dout_1_re,
           doutVld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dinReg2_0_re;  // sfix16_En15
  input   signed [15:0] coefIn_0;  // sfix16_En15
  input   signed [15:0] coefIn_1;  // sfix16_En15
  input   signed [15:0] coefIn_2;  // sfix16_En15
  input   signed [15:0] coefIn_3;  // sfix16_En15
  input   signed [15:0] coefIn_4;  // sfix16_En15
  input   signed [15:0] coefIn_5;  // sfix16_En15
  input   signed [15:0] coefIn_6;  // sfix16_En15
  input   signed [15:0] coefIn_7;  // sfix16_En15
  input   signed [15:0] coefIn_8;  // sfix16_En15
  input   signed [15:0] coefIn_9;  // sfix16_En15
  input   signed [15:0] coefIn_10;  // sfix16_En15
  input   dinRegVld;
  input   syncReset;
  output  signed [32:0] dout_1_re;  // sfix33_En30
  output  doutVld;


  reg  [9:0] intdelay_reg;  // ufix1 [10]
  wire vldShift;
  wire vldOutTmp;
  wire signed [32:0] ZERO_OUT;  // sfix33_En30
  wire signed [47:0] addin;  // sfix48_En30
  wire signed [15:0] dinDly2;  // sfix16_En15
  reg signed [15:0] dinPreAdd;  // sfix16_En15
  wire signed [15:0] dinDly2_1;  // sfix16_En15
  wire signed [47:0] tapout;  // sfix48_En30
  wire signed [15:0] dinDly2_2;  // sfix16_En15
  wire signed [47:0] tapout_1;  // sfix48_En30
  wire signed [15:0] dinDly2_3;  // sfix16_En15
  wire signed [47:0] tapout_2;  // sfix48_En30
  wire signed [15:0] dinDly2_4;  // sfix16_En15
  wire signed [47:0] tapout_3;  // sfix48_En30
  wire signed [47:0] tapout_4;  // sfix48_En30
  wire signed [15:0] dinDly2_5;  // sfix16_En15
  wire signed [47:0] tapout_5;  // sfix48_En30
  wire tapoutVld;
  wire signed [32:0] dout_cast;  // sfix33_En30
  wire signed [32:0] muxOut;  // sfix33_En30
  reg signed [32:0] dout_1_re_1;  // sfix33_En30
  reg  doutVld_1;


  always @(posedge clk or negedge reset)
    begin : intdelay_process
      if (reset == 1'b0) begin
        intdelay_reg <= {10{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg <= {10{1'b0}};
          end
          else begin
            if (dinRegVld) begin
              intdelay_reg[0] <= dinRegVld;
              intdelay_reg[32'sd9:32'sd1] <= intdelay_reg[32'sd8:32'sd0];
            end
          end
        end
      end
    end

  assign vldShift = intdelay_reg[9];

  assign vldOutTmp = dinRegVld & vldShift;

  assign ZERO_OUT = 33'sh000000000;

  assign addin = 48'sh000000000000;

  always @(posedge clk or negedge reset)
    begin : intdelay_1_process
      if (reset == 1'b0) begin
        dinPreAdd <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinPreAdd <= 16'sb0000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinPreAdd <= dinDly2;
            end
          end
        end
      end
    end

  FilterTapSystolicPreAddWvlIn u_FilterTap_1 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinReg2_0_re),  // sfix16_En15
                                              .dinPreAdd(dinPreAdd),  // sfix16_En15
                                              .coefIn_0(coefIn_0),  // sfix16_En15
                                              .addin(addin),  // sfix48_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_1),  // sfix16_En15
                                              .tapout(tapout)  // sfix48_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_2 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_1),  // sfix16_En15
                                              .dinPreAdd(dinPreAdd),  // sfix16_En15
                                              .coefIn_0(coefIn_1),  // sfix16_En15
                                              .addin(tapout),  // sfix48_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_2),  // sfix16_En15
                                              .tapout(tapout_1)  // sfix48_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_3 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_2),  // sfix16_En15
                                              .dinPreAdd(dinPreAdd),  // sfix16_En15
                                              .coefIn_0(coefIn_2),  // sfix16_En15
                                              .addin(tapout_1),  // sfix48_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_3),  // sfix16_En15
                                              .tapout(tapout_2)  // sfix48_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_4 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_3),  // sfix16_En15
                                              .dinPreAdd(dinPreAdd),  // sfix16_En15
                                              .coefIn_0(coefIn_3),  // sfix16_En15
                                              .addin(tapout_2),  // sfix48_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_4),  // sfix16_En15
                                              .tapout(tapout_3)  // sfix48_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_5 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_4),  // sfix16_En15
                                              .dinPreAdd(dinPreAdd),  // sfix16_En15
                                              .coefIn_0(coefIn_4),  // sfix16_En15
                                              .addin(tapout_3),  // sfix48_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2),  // sfix16_En15
                                              .tapout(tapout_4)  // sfix48_En30
                                              );

  FilterTapSystolicWvldInC0 u_FilterTap_6 (.clk(clk),
                                           .reset(reset),
                                           .enb(enb),
                                           .dinReg2_0_re(dinDly2),  // sfix16_En15
                                           .addin(tapout_4),  // sfix48_En30
                                           .dinRegVld(dinRegVld),
                                           .syncReset(syncReset),
                                           .dinDly2(dinDly2_5),  // sfix16_En15
                                           .tapout(tapout_5),  // sfix48_En30
                                           .tapoutVld(tapoutVld)
                                           );

  assign dout_cast = tapout_5[32:0];

  assign muxOut = (vldOutTmp == 1'b0 ? ZERO_OUT :
              dout_cast);

  always @(posedge clk or negedge reset)
    begin : intdelay_2_process
      if (reset == 1'b0) begin
        dout_1_re_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dout_1_re_1 <= 33'sh000000000;
          end
          else begin
            dout_1_re_1 <= muxOut;
          end
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : intdelay_3_process
      if (reset == 1'b0) begin
        doutVld_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            doutVld_1 <= 1'b0;
          end
          else begin
            doutVld_1 <= vldOutTmp;
          end
        end
      end
    end

  assign dout_1_re = dout_1_re_1;

  assign doutVld = doutVld_1;

endmodule  // subFilter

