# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/xfft_256pt_32bit/xfft_256pt_32bit.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_256pt_32bit || ORIG_REF_NAME==xfft_256pt_32bit} -quiet] -quiet
