function [dataOut,validOut] = hilbert_fir_filter_1027(dataIn,validIn,resetIn)
% Generated by HDL IP Designer.

persistent ipblock

if isempty(ipblock)
    ipblock = dsphdl.FIRFilter(...
        'Numerator',[-0.171618920927293 -2.74717688367269e-16 -0.292172654639327 2.3743215420913e-16 -1 0 1 -2.3743215420913e-16 0.292172654639327 2.74717688367269e-16 0.171618920927293],...
        'ResetInputPort',true,...
        'CoefficientsDataType',numerictype(1,16,14));
end

[dataOut,validOut] = ipblock(dataIn,validIn,resetIn);

end
