@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Oct 08 18:37:28 -0400 2025
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim bartlett_datapath_tb_auto_behav -key {Behavioral:sim_1:Functional:bartlett_datapath_tb_auto} -tclbatch bartlett_datapath_tb_auto.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/Aweso/Verilog/Aquapack/bartlett/bartlett_time_domain_tb_behav.wcfg -view C:/Users/Aweso/Verilog/Aquapack/bartlett/complex_matrix_hadamard_tb_behav.wcfg -view C:/Users/Aweso/Verilog/Aquapack/bartlett/scalar_divide_tb_behav.wcfg -view C:/Users/Aweso/Verilog/Aquapack/bartlett/rxx_tb_16_behav.wcfg -view C:/Users/Aweso/Verilog/Aquapack/bartlett/bartlett_datapath_tb_behav.wcfg -log simulate.log"
call xsim  bartlett_datapath_tb_auto_behav -key {Behavioral:sim_1:Functional:bartlett_datapath_tb_auto} -tclbatch bartlett_datapath_tb_auto.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/Aweso/Verilog/Aquapack/bartlett/bartlett_time_domain_tb_behav.wcfg -view C:/Users/Aweso/Verilog/Aquapack/bartlett/complex_matrix_hadamard_tb_behav.wcfg -view C:/Users/Aweso/Verilog/Aquapack/bartlett/scalar_divide_tb_behav.wcfg -view C:/Users/Aweso/Verilog/Aquapack/bartlett/rxx_tb_16_behav.wcfg -view C:/Users/Aweso/Verilog/Aquapack/bartlett/bartlett_datapath_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
