#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Nov 05 19:39:53 EST 2025
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim SW9_tb_func_synth -key {Post-Synthesis:sim_1:Functional:SW9_tb} -tclbatch SW9_tb.tcl -view /home/bigpi/AMD/Vivado/2022.2/Projects/SW9A-AcousticsFPGA/SW9_tb_behav.wcfg -log simulate.log"
xsim SW9_tb_func_synth -key {Post-Synthesis:sim_1:Functional:SW9_tb} -tclbatch SW9_tb.tcl -view /home/bigpi/AMD/Vivado/2022.2/Projects/SW9A-AcousticsFPGA/SW9_tb_behav.wcfg -log simulate.log

