## This file is a general .xdc for the CmodA7 rev. B
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

## 12 MHz Clock Signal
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports sysclk]
create_clock -period 83.330 -name sys_clk_pin -waveform {0.000 41.660} -add [get_ports sysclk]

## LEDs
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports {led[1]}]

## RGB LED
#set_property -dict { PACKAGE_PIN B17   IOSTANDARD LVCMOS33 } [get_ports { led0_b }]; #IO_L14N_T2_SRCC_16 Sch=led0_b
#set_property -dict { PACKAGE_PIN B16   IOSTANDARD LVCMOS33 } [get_ports { led0_g }]; #IO_L13N_T2_MRCC_16 Sch=led0_g
#set_property -dict { PACKAGE_PIN C17   IOSTANDARD LVCMOS33 } [get_ports { led0_r }]; #IO_L14P_T2_SRCC_16 Sch=led0_r

## Buttons
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports {btn[0]}]
#set_property -dict { PACKAGE_PIN B18   IOSTANDARD LVCMOS33 } [get_ports { btn[1] }]; #IO_L19P_T3_16 Sch=btn[1]

## Pmod Header JA
#set_property -dict { PACKAGE_PIN G17   IOSTANDARD LVCMOS33 } [get_ports { ja[0] }]; #IO_L5N_T0_D07_14 Sch=ja[1]
#set_property -dict { PACKAGE_PIN G19   IOSTANDARD LVCMOS33 } [get_ports { ja[1] }]; #IO_L4N_T0_D05_14 Sch=ja[2]
#set_property -dict { PACKAGE_PIN N18   IOSTANDARD LVCMOS33 } [get_ports { ja[2] }]; #IO_L9P_T1_DQS_14 Sch=ja[3]
#set_property -dict { PACKAGE_PIN L18   IOSTANDARD LVCMOS33 } [get_ports { ja[3] }]; #IO_L8P_T1_D11_14 Sch=ja[4]
#set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { ja[4] }]; #IO_L5P_T0_D06_14 Sch=ja[7]
#set_property -dict { PACKAGE_PIN H19   IOSTANDARD LVCMOS33 } [get_ports { ja[5] }]; #IO_L4P_T0_D04_14 Sch=ja[8]
#set_property -dict { PACKAGE_PIN J19   IOSTANDARD LVCMOS33 } [get_ports { ja[6] }]; #IO_L6N_T0_D08_VREF_14 Sch=ja[9]
#set_property -dict { PACKAGE_PIN K18   IOSTANDARD LVCMOS33 } [get_ports { ja[7] }]; #IO_L8N_T1_D12_14 Sch=ja[10]

## Analog XADC Pins
## Only declare these if you want to use pins 15 and 16 as single ended analog inputs. pin 15 -> vaux4, pin16 -> vaux12
#set_property -dict { PACKAGE_PIN G2    IOSTANDARD LVCMOS33 } [get_ports { xa_n[0] }]; #IO_L1N_T0_AD4N_35 Sch=ain_n[15]
#set_property -dict { PACKAGE_PIN G3    IOSTANDARD LVCMOS33 } [get_ports { xa_p[0] }]; #IO_L1P_T0_AD4P_35 Sch=ain_p[15]
#set_property -dict { PACKAGE_PIN J2    IOSTANDARD LVCMOS33 } [get_ports { xa_n[1] }]; #IO_L2N_T0_AD12N_35 Sch=ain_n[16]
#set_property -dict { PACKAGE_PIN H2    IOSTANDARD LVCMOS33 } [get_ports { xa_p[1] }]; #IO_L2P_T0_AD12P_35 Sch=ain_p[16]

## GPIO Pins
## Pins 15 and 16 should remain commented if using them as analog inputs
set_property -dict {PACKAGE_PIN M3 IOSTANDARD LVCMOS33} [get_ports pio1]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS33} [get_ports pio2]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports pio3]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports pio4]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports pio5]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports pio6]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports pio7]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports pio8]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports pio9]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports pio10]
set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS33} [get_ports pio11]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports pio12]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports pio13]
set_property -dict {PACKAGE_PIN L2 IOSTANDARD LVCMOS33} [get_ports pio14]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports pio17]
set_property -dict {PACKAGE_PIN N3 IOSTANDARD LVCMOS33} [get_ports pio18]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports pio19]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports pio20]
set_property -dict {PACKAGE_PIN N1 IOSTANDARD LVCMOS33} [get_ports pio21]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVCMOS33} [get_ports pio22]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVCMOS33} [get_ports pio23]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports pio26]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports pio27]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports pio28]
set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVCMOS33} [get_ports pio29]
set_property -dict {PACKAGE_PIN T2 IOSTANDARD LVCMOS33} [get_ports pio30]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports pio31]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVCMOS33} [get_ports pio32]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS33} [get_ports pio33]
set_property -dict {PACKAGE_PIN W3 IOSTANDARD LVCMOS33} [get_ports pio34]
set_property -dict {PACKAGE_PIN V3 IOSTANDARD LVCMOS33} [get_ports pio35]
set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS33} [get_ports pio36]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports pio37]
set_property -dict {PACKAGE_PIN U4 IOSTANDARD LVCMOS33} [get_ports pio38]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports pio39]
set_property -dict {PACKAGE_PIN W4 IOSTANDARD LVCMOS33} [get_ports pio40]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS33} [get_ports pio41]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports pio42]
set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVCMOS33} [get_ports pio43]
set_property -dict {PACKAGE_PIN U3 IOSTANDARD LVCMOS33} [get_ports pio44]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports pio45]
set_property -dict {PACKAGE_PIN W7 IOSTANDARD LVCMOS33} [get_ports pio46]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS33} [get_ports pio47]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS33} [get_ports pio48]

## UART
#set_property -dict { PACKAGE_PIN J18   IOSTANDARD LVCMOS33 } [get_ports { uart_rxd_out }]; #IO_L7N_T1_D10_14 Sch=uart_rxd_out
#set_property -dict { PACKAGE_PIN J17   IOSTANDARD LVCMOS33 } [get_ports { uart_txd_in  }]; #IO_L7P_T1_D09_14 Sch=uart_txd_in

## Crypto 1 Wire Interface
#set_property -dict { PACKAGE_PIN D17   IOSTANDARD LVCMOS33 } [get_ports { crypto_sda }]; #IO_0_14 Sch=crypto_sda

## QSPI
#set_property -dict { PACKAGE_PIN K19   IOSTANDARD LVCMOS33 } [get_ports { qspi_cs    }]; #IO_L6P_T0_FCS_B_14 Sch=qspi_cs
#set_property -dict { PACKAGE_PIN D18   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[0] }]; #IO_L1P_T0_D00_MOSI_14 Sch=qspi_dq[0]
#set_property -dict { PACKAGE_PIN D19   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[1] }]; #IO_L1N_T0_D01_DIN_14 Sch=qspi_dq[1]
#set_property -dict { PACKAGE_PIN G18   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[2] }]; #IO_L2P_T0_D02_14 Sch=qspi_dq[2]
#set_property -dict { PACKAGE_PIN F18   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[3] }]; #IO_L2N_T0_D03_14 Sch=qspi_dq[3]

## Cellular RAM
#set_property -dict { PACKAGE_PIN M18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[0]  }]; #IO_L11P_T1_SRCC_14 Sch=sram- a[0]
#set_property -dict { PACKAGE_PIN M19   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[1]  }]; #IO_L11N_T1_SRCC_14 Sch=sram- a[1]
#set_property -dict { PACKAGE_PIN K17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[2]  }]; #IO_L12N_T1_MRCC_14 Sch=sram- a[2]
#set_property -dict { PACKAGE_PIN N17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[3]  }]; #IO_L13P_T2_MRCC_14 Sch=sram- a[3]
#set_property -dict { PACKAGE_PIN P17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[4]  }]; #IO_L13N_T2_MRCC_14 Sch=sram- a[4]
#set_property -dict { PACKAGE_PIN P18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[5]  }]; #IO_L14P_T2_SRCC_14 Sch=sram- a[5]
#set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[6]  }]; #IO_L14N_T2_SRCC_14 Sch=sram- a[6]
#set_property -dict { PACKAGE_PIN W19   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[7]  }]; #IO_L16N_T2_A15_D31_14 Sch=sram- a[7]
#set_property -dict { PACKAGE_PIN U19   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[8]  }]; #IO_L15P_T2_DQS_RDWR_B_14 Sch=sram- a[8]
#set_property -dict { PACKAGE_PIN V19   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[9]  }]; #IO_L15N_T2_DQS_DOUT_CSO_B_14 Sch=sram- a[9]
#set_property -dict { PACKAGE_PIN W18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[10] }]; #IO_L16P_T2_CSI_B_14 Sch=sram- a[10]
#set_property -dict { PACKAGE_PIN T17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[11] }]; #IO_L17P_T2_A14_D30_14 Sch=sram- a[11]
#set_property -dict { PACKAGE_PIN T18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[12] }]; #IO_L17N_T2_A13_D29_14 Sch=sram- a[12]
#set_property -dict { PACKAGE_PIN U17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[13] }]; #IO_L18P_T2_A12_D28_14 Sch=sram- a[13]
#set_property -dict { PACKAGE_PIN U18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[14] }]; #IO_L18N_T2_A11_D27_14 Sch=sram- a[14]
#set_property -dict { PACKAGE_PIN V16   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[15] }]; #IO_L19P_T3_A10_D26_14 Sch=sram- a[15]
#set_property -dict { PACKAGE_PIN W16   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[16] }]; #IO_L20P_T3_A08_D24_14 Sch=sram- a[16]
#set_property -dict { PACKAGE_PIN W17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[17] }]; #IO_L20N_T3_A07_D23_14 Sch=sram- a[17]
#set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[18] }]; #IO_L21P_T3_DQS_14 Sch=sram- a[18]
#set_property -dict { PACKAGE_PIN W15   IOSTANDARD LVCMOS33 } [get_ports { MemDB[0]   }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=sram-dq[0]
#set_property -dict { PACKAGE_PIN W13   IOSTANDARD LVCMOS33 } [get_ports { MemDB[1]   }]; #IO_L22P_T3_A05_D21_14 Sch=sram-dq[1]
#set_property -dict { PACKAGE_PIN W14   IOSTANDARD LVCMOS33 } [get_ports { MemDB[2]   }]; #IO_L22N_T3_A04_D20_14 Sch=sram-dq[2]
#set_property -dict { PACKAGE_PIN U15   IOSTANDARD LVCMOS33 } [get_ports { MemDB[3]   }]; #IO_L23P_T3_A03_D19_14 Sch=sram-dq[3]
#set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 } [get_ports { MemDB[4]   }]; #IO_L23N_T3_A02_D18_14 Sch=sram-dq[4]
#set_property -dict { PACKAGE_PIN V13   IOSTANDARD LVCMOS33 } [get_ports { MemDB[5]   }]; #IO_L24P_T3_A01_D17_14 Sch=sram-dq[5]
#set_property -dict { PACKAGE_PIN V14   IOSTANDARD LVCMOS33 } [get_ports { MemDB[6]   }]; #IO_L24N_T3_A00_D16_14 Sch=sram-dq[6]
#set_property -dict { PACKAGE_PIN U14   IOSTANDARD LVCMOS33 } [get_ports { MemDB[7]   }]; #IO_25_14 Sch=sram-dq[7]
#set_property -dict { PACKAGE_PIN P19   IOSTANDARD LVCMOS33 } [get_ports { RamOEn     }]; #IO_L10P_T1_D14_14 Sch=sram-oe
#set_property -dict { PACKAGE_PIN R19   IOSTANDARD LVCMOS33 } [get_ports { RamWEn     }]; #IO_L10N_T1_D15_14 Sch=sram-we
#set_property -dict { PACKAGE_PIN N19   IOSTANDARD LVCMOS33 } [get_ports { RamCEn     }]; #IO_L9N_T1_DQS_D13_14 Sch=sram-ce




set_property MARK_DEBUG true [get_nets {top_inst/rx_data[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/rx_data[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/rx_data[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/rx_data[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/rx_data[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/rx_data[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/rx_data[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/rx_data[7]}]
set_property MARK_DEBUG true [get_nets top_inst/rx_ready]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[7]}]
set_property MARK_DEBUG true [get_nets top_inst/Word_To_Send_en]
set_property MARK_DEBUG false [get_nets pio1_IBUF]
set_property MARK_DEBUG false [get_nets pio2_OBUF]
set_property MARK_DEBUG false [get_nets pio18_IBUF]
set_property MARK_DEBUG false [get_nets sysclk_IBUF]
set_property MARK_DEBUG false [get_nets top_inst/UART_clk]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[10]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[13]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[16]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[20]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[24]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[30]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[31]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[11]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[15]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[18]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[25]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[12]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[14]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[17]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[22]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[28]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[29]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[8]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[9]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[19]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[21]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[23]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[26]}]
set_property MARK_DEBUG true [get_nets {top_inst/threshold[27]}]
set_property MARK_DEBUG true [get_nets {top_inst/min_frequency[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/min_frequency[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/min_frequency[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/min_frequency[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/min_frequency[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/min_frequency[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/min_frequency[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/min_frequency[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/max_frequency[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/max_frequency[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/max_frequency[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/max_frequency[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/max_frequency[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/max_frequency[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/max_frequency[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/max_frequency[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/Q[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/Q[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/Q[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in_0[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in_0[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in_0[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in_0[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in_0[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in_0[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in_0[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in_0[7]}]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_1]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_2]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_4]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_5]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_6]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_7]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_8]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_9]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_0]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_3]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_10]
connect_debug_port u_ila_0/probe1 [get_nets [list {top_inst/p_0_in_0[0]} {top_inst/p_0_in_0[1]} {top_inst/p_0_in_0[2]} {top_inst/p_0_in_0[3]} {top_inst/p_0_in_0[4]} {top_inst/p_0_in_0[5]} {top_inst/p_0_in_0[6]} {top_inst/p_0_in_0[7]}]]
connect_debug_port command_reader_ila/probe0 [get_nets [list {top_inst/Q[0]} {top_inst/Q[1]} {top_inst/Q[2]}]]
connect_debug_port command_reader_ila/probe1 [get_nets [list {top_inst/threshold[0]} {top_inst/threshold[1]} {top_inst/threshold[2]} {top_inst/threshold[3]} {top_inst/threshold[4]} {top_inst/threshold[5]} {top_inst/threshold[6]} {top_inst/threshold[7]} {top_inst/threshold[8]} {top_inst/threshold[9]} {top_inst/threshold[10]} {top_inst/threshold[11]} {top_inst/threshold[12]} {top_inst/threshold[13]} {top_inst/threshold[14]} {top_inst/threshold[15]} {top_inst/threshold[16]} {top_inst/threshold[17]} {top_inst/threshold[18]} {top_inst/threshold[19]} {top_inst/threshold[20]} {top_inst/threshold[21]} {top_inst/threshold[22]} {top_inst/threshold[23]} {top_inst/threshold[24]} {top_inst/threshold[25]} {top_inst/threshold[26]} {top_inst/threshold[27]} {top_inst/threshold[28]} {top_inst/threshold[29]} {top_inst/threshold[30]} {top_inst/threshold[31]}]]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list top_inst/clk_wiz_inst/inst/clk_100mhz]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {top_inst/threshold_0[0]} {top_inst/threshold_0[1]} {top_inst/threshold_0[2]} {top_inst/threshold_0[3]} {top_inst/threshold_0[4]} {top_inst/threshold_0[5]} {top_inst/threshold_0[6]} {top_inst/threshold_0[7]} {top_inst/threshold_0[8]} {top_inst/threshold_0[9]} {top_inst/threshold_0[10]} {top_inst/threshold_0[11]} {top_inst/threshold_0[12]} {top_inst/threshold_0[13]} {top_inst/threshold_0[14]} {top_inst/threshold_0[15]} {top_inst/threshold_0[16]} {top_inst/threshold_0[17]} {top_inst/threshold_0[18]} {top_inst/threshold_0[19]} {top_inst/threshold_0[20]} {top_inst/threshold_0[21]} {top_inst/threshold_0[22]} {top_inst/threshold_0[23]} {top_inst/threshold_0[24]} {top_inst/threshold_0[25]} {top_inst/threshold_0[26]} {top_inst/threshold_0[27]} {top_inst/threshold_0[28]} {top_inst/threshold_0[29]} {top_inst/threshold_0[30]} {top_inst/threshold_0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {top_inst/max_frequency[0]} {top_inst/max_frequency[1]} {top_inst/max_frequency[2]} {top_inst/max_frequency[3]} {top_inst/max_frequency[4]} {top_inst/max_frequency[5]} {top_inst/max_frequency[6]} {top_inst/max_frequency[7]} {top_inst/max_frequency[8]} {top_inst/max_frequency[9]} {top_inst/max_frequency[10]} {top_inst/max_frequency[11]} {top_inst/max_frequency[12]} {top_inst/max_frequency[13]} {top_inst/max_frequency[14]} {top_inst/max_frequency[15]} {top_inst/max_frequency[16]} {top_inst/max_frequency[17]} {top_inst/max_frequency[18]} {top_inst/max_frequency[19]} {top_inst/max_frequency[20]} {top_inst/max_frequency[21]} {top_inst/max_frequency[22]} {top_inst/max_frequency[23]} {top_inst/max_frequency[24]} {top_inst/max_frequency[25]} {top_inst/max_frequency[26]} {top_inst/max_frequency[27]} {top_inst/max_frequency[28]} {top_inst/max_frequency[29]} {top_inst/max_frequency[30]} {top_inst/max_frequency[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {top_inst/Word_To_Send[0]} {top_inst/Word_To_Send[1]} {top_inst/Word_To_Send[2]} {top_inst/Word_To_Send[3]} {top_inst/Word_To_Send[4]} {top_inst/Word_To_Send[5]} {top_inst/Word_To_Send[6]} {top_inst/Word_To_Send[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {top_inst/min_frequency[0]} {top_inst/min_frequency[1]} {top_inst/min_frequency[2]} {top_inst/min_frequency[3]} {top_inst/min_frequency[4]} {top_inst/min_frequency[5]} {top_inst/min_frequency[6]} {top_inst/min_frequency[7]} {top_inst/min_frequency[8]} {top_inst/min_frequency[9]} {top_inst/min_frequency[10]} {top_inst/min_frequency[11]} {top_inst/min_frequency[12]} {top_inst/min_frequency[13]} {top_inst/min_frequency[14]} {top_inst/min_frequency[15]} {top_inst/min_frequency[16]} {top_inst/min_frequency[17]} {top_inst/min_frequency[18]} {top_inst/min_frequency[19]} {top_inst/min_frequency[20]} {top_inst/min_frequency[21]} {top_inst/min_frequency[22]} {top_inst/min_frequency[23]} {top_inst/min_frequency[24]} {top_inst/min_frequency[25]} {top_inst/min_frequency[26]} {top_inst/min_frequency[27]} {top_inst/min_frequency[28]} {top_inst/min_frequency[29]} {top_inst/min_frequency[30]} {top_inst/min_frequency[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {top_inst/rx_data[0]} {top_inst/rx_data[1]} {top_inst/rx_data[2]} {top_inst/rx_data[3]} {top_inst/rx_data[4]} {top_inst/rx_data[5]} {top_inst/rx_data[6]} {top_inst/rx_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list top_inst/rx_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list top_inst/Word_To_Send_en]]
set_property MARK_DEBUG true [get_nets {top_inst/UART_inst/UART_TX_inst/TX_Bit_sel[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_inst/UART_TX_inst/TX_Bit_sel[2]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_100mhz]
