## This file is a general .xdc for the CmodA7 rev. B
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

## 12 MHz Clock Signal
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports sysclk]
create_clock -period 83.330 -name sys_clk_pin -waveform {0.000 41.660} -add [get_ports sysclk]

## LEDs
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports {led[1]}]

## RGB LED
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports led0_b]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports led0_g]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports led0_r]

## Buttons
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports {btn[0]}]
#set_property -dict { PACKAGE_PIN B18   IOSTANDARD LVCMOS33 } [get_ports { btn[1] }]; #IO_L19P_T3_16 Sch=btn[1]

## Pmod Header JA
#set_property -dict { PACKAGE_PIN G17   IOSTANDARD LVCMOS33 } [get_ports { ja[0] }]; #IO_L5N_T0_D07_14 Sch=ja[1]
#set_property -dict { PACKAGE_PIN G19   IOSTANDARD LVCMOS33 } [get_ports { ja[1] }]; #IO_L4N_T0_D05_14 Sch=ja[2]
#set_property -dict { PACKAGE_PIN N18   IOSTANDARD LVCMOS33 } [get_ports { ja[2] }]; #IO_L9P_T1_DQS_14 Sch=ja[3]
#set_property -dict { PACKAGE_PIN L18   IOSTANDARD LVCMOS33 } [get_ports { ja[3] }]; #IO_L8P_T1_D11_14 Sch=ja[4]
#set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { ja[4] }]; #IO_L5P_T0_D06_14 Sch=ja[7]
#set_property -dict { PACKAGE_PIN H19   IOSTANDARD LVCMOS33 } [get_ports { ja[5] }]; #IO_L4P_T0_D04_14 Sch=ja[8]
#set_property -dict { PACKAGE_PIN J19   IOSTANDARD LVCMOS33 } [get_ports { ja[6] }]; #IO_L6N_T0_D08_VREF_14 Sch=ja[9]
#set_property -dict { PACKAGE_PIN K18   IOSTANDARD LVCMOS33 } [get_ports { ja[7] }]; #IO_L8N_T1_D12_14 Sch=ja[10]

## Analog XADC Pins
## Only declare these if you want to use pins 15 and 16 as single ended analog inputs. pin 15 -> vaux4, pin16 -> vaux12
#set_property -dict { PACKAGE_PIN G2    IOSTANDARD LVCMOS33 } [get_ports { xa_n[0] }]; #IO_L1N_T0_AD4N_35 Sch=ain_n[15]
#set_property -dict { PACKAGE_PIN G3    IOSTANDARD LVCMOS33 } [get_ports { xa_p[0] }]; #IO_L1P_T0_AD4P_35 Sch=ain_p[15]
#set_property -dict { PACKAGE_PIN J2    IOSTANDARD LVCMOS33 } [get_ports { xa_n[1] }]; #IO_L2N_T0_AD12N_35 Sch=ain_n[16]
#set_property -dict { PACKAGE_PIN H2    IOSTANDARD LVCMOS33 } [get_ports { xa_p[1] }]; #IO_L2P_T0_AD12P_35 Sch=ain_p[16]

## GPIO Pins
## Pins 15 and 16 should remain commented if using them as analog inputs
set_property -dict {PACKAGE_PIN M3 IOSTANDARD LVCMOS33} [get_ports pio1]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS33} [get_ports pio2]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports pio3]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports pio4]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports pio5]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports pio6]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports pio7]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports pio8]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports pio9]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports pio10]
set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS33} [get_ports pio11]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports pio12]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports pio13]
set_property -dict {PACKAGE_PIN L2 IOSTANDARD LVCMOS33} [get_ports pio14]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports pio17]
set_property -dict {PACKAGE_PIN N3 IOSTANDARD LVCMOS33} [get_ports pio18]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports pio19]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports pio20]
set_property -dict {PACKAGE_PIN N1 IOSTANDARD LVCMOS33} [get_ports pio21]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVCMOS33} [get_ports pio22]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVCMOS33} [get_ports pio23]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports pio26]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports pio27]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports pio28]
set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVCMOS33} [get_ports pio29]
set_property -dict {PACKAGE_PIN T2 IOSTANDARD LVCMOS33} [get_ports pio30]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports pio31]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVCMOS33} [get_ports pio32]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS33} [get_ports pio33]
set_property -dict {PACKAGE_PIN W3 IOSTANDARD LVCMOS33} [get_ports pio34]
set_property -dict {PACKAGE_PIN V3 IOSTANDARD LVCMOS33} [get_ports pio35]
set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS33} [get_ports pio36]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports pio37]
set_property -dict {PACKAGE_PIN U4 IOSTANDARD LVCMOS33} [get_ports pio38]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports pio39]
set_property -dict {PACKAGE_PIN W4 IOSTANDARD LVCMOS33} [get_ports pio40]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS33} [get_ports pio41]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports pio42]
set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVCMOS33} [get_ports pio43]
set_property -dict {PACKAGE_PIN U3 IOSTANDARD LVCMOS33} [get_ports pio44]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports pio45]
set_property -dict {PACKAGE_PIN W7 IOSTANDARD LVCMOS33} [get_ports pio46]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS33} [get_ports pio47]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS33} [get_ports pio48]

## UART
set_property -dict { PACKAGE_PIN J18   IOSTANDARD LVCMOS33 } [get_ports { uart_rxd_out }]; #IO_L7N_T1_D10_14 Sch=uart_rxd_out
set_property -dict { PACKAGE_PIN J17   IOSTANDARD LVCMOS33 } [get_ports { uart_txd_in  }]; #IO_L7P_T1_D09_14 Sch=uart_txd_in

## Crypto 1 Wire Interface
#set_property -dict { PACKAGE_PIN D17   IOSTANDARD LVCMOS33 } [get_ports { crypto_sda }]; #IO_0_14 Sch=crypto_sda

## QSPI
#set_property -dict { PACKAGE_PIN K19   IOSTANDARD LVCMOS33 } [get_ports { qspi_cs    }]; #IO_L6P_T0_FCS_B_14 Sch=qspi_cs
#set_property -dict { PACKAGE_PIN D18   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[0] }]; #IO_L1P_T0_D00_MOSI_14 Sch=qspi_dq[0]
#set_property -dict { PACKAGE_PIN D19   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[1] }]; #IO_L1N_T0_D01_DIN_14 Sch=qspi_dq[1]
#set_property -dict { PACKAGE_PIN G18   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[2] }]; #IO_L2P_T0_D02_14 Sch=qspi_dq[2]
#set_property -dict { PACKAGE_PIN F18   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[3] }]; #IO_L2N_T0_D03_14 Sch=qspi_dq[3]

## Cellular RAM
#set_property -dict { PACKAGE_PIN M18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[0]  }]; #IO_L11P_T1_SRCC_14 Sch=sram- a[0]
#set_property -dict { PACKAGE_PIN M19   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[1]  }]; #IO_L11N_T1_SRCC_14 Sch=sram- a[1]
#set_property -dict { PACKAGE_PIN K17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[2]  }]; #IO_L12N_T1_MRCC_14 Sch=sram- a[2]
#set_property -dict { PACKAGE_PIN N17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[3]  }]; #IO_L13P_T2_MRCC_14 Sch=sram- a[3]
#set_property -dict { PACKAGE_PIN P17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[4]  }]; #IO_L13N_T2_MRCC_14 Sch=sram- a[4]
#set_property -dict { PACKAGE_PIN P18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[5]  }]; #IO_L14P_T2_SRCC_14 Sch=sram- a[5]
#set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[6]  }]; #IO_L14N_T2_SRCC_14 Sch=sram- a[6]
#set_property -dict { PACKAGE_PIN W19   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[7]  }]; #IO_L16N_T2_A15_D31_14 Sch=sram- a[7]
#set_property -dict { PACKAGE_PIN U19   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[8]  }]; #IO_L15P_T2_DQS_RDWR_B_14 Sch=sram- a[8]
#set_property -dict { PACKAGE_PIN V19   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[9]  }]; #IO_L15N_T2_DQS_DOUT_CSO_B_14 Sch=sram- a[9]
#set_property -dict { PACKAGE_PIN W18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[10] }]; #IO_L16P_T2_CSI_B_14 Sch=sram- a[10]
#set_property -dict { PACKAGE_PIN T17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[11] }]; #IO_L17P_T2_A14_D30_14 Sch=sram- a[11]
#set_property -dict { PACKAGE_PIN T18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[12] }]; #IO_L17N_T2_A13_D29_14 Sch=sram- a[12]
#set_property -dict { PACKAGE_PIN U17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[13] }]; #IO_L18P_T2_A12_D28_14 Sch=sram- a[13]
#set_property -dict { PACKAGE_PIN U18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[14] }]; #IO_L18N_T2_A11_D27_14 Sch=sram- a[14]
#set_property -dict { PACKAGE_PIN V16   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[15] }]; #IO_L19P_T3_A10_D26_14 Sch=sram- a[15]
#set_property -dict { PACKAGE_PIN W16   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[16] }]; #IO_L20P_T3_A08_D24_14 Sch=sram- a[16]
#set_property -dict { PACKAGE_PIN W17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[17] }]; #IO_L20N_T3_A07_D23_14 Sch=sram- a[17]
#set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[18] }]; #IO_L21P_T3_DQS_14 Sch=sram- a[18]
#set_property -dict { PACKAGE_PIN W15   IOSTANDARD LVCMOS33 } [get_ports { MemDB[0]   }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=sram-dq[0]
#set_property -dict { PACKAGE_PIN W13   IOSTANDARD LVCMOS33 } [get_ports { MemDB[1]   }]; #IO_L22P_T3_A05_D21_14 Sch=sram-dq[1]
#set_property -dict { PACKAGE_PIN W14   IOSTANDARD LVCMOS33 } [get_ports { MemDB[2]   }]; #IO_L22N_T3_A04_D20_14 Sch=sram-dq[2]
#set_property -dict { PACKAGE_PIN U15   IOSTANDARD LVCMOS33 } [get_ports { MemDB[3]   }]; #IO_L23P_T3_A03_D19_14 Sch=sram-dq[3]
#set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 } [get_ports { MemDB[4]   }]; #IO_L23N_T3_A02_D18_14 Sch=sram-dq[4]
#set_property -dict { PACKAGE_PIN V13   IOSTANDARD LVCMOS33 } [get_ports { MemDB[5]   }]; #IO_L24P_T3_A01_D17_14 Sch=sram-dq[5]
#set_property -dict { PACKAGE_PIN V14   IOSTANDARD LVCMOS33 } [get_ports { MemDB[6]   }]; #IO_L24N_T3_A00_D16_14 Sch=sram-dq[6]
#set_property -dict { PACKAGE_PIN U14   IOSTANDARD LVCMOS33 } [get_ports { MemDB[7]   }]; #IO_25_14 Sch=sram-dq[7]
#set_property -dict { PACKAGE_PIN P19   IOSTANDARD LVCMOS33 } [get_ports { RamOEn     }]; #IO_L10P_T1_D14_14 Sch=sram-oe
#set_property -dict { PACKAGE_PIN R19   IOSTANDARD LVCMOS33 } [get_ports { RamWEn     }]; #IO_L10N_T1_D15_14 Sch=sram-we
#set_property -dict { PACKAGE_PIN N19   IOSTANDARD LVCMOS33 } [get_ports { RamCEn     }]; #IO_L9N_T1_DQS_D13_14 Sch=sram-ce




set_property MARK_DEBUG true [get_nets top_inst/p_0_in]
set_property MARK_DEBUG true [get_nets top_inst/SPI_WRAPPER_inst_n_32]
set_property MARK_DEBUG true [get_nets top_inst/SPI_WRAPPER_inst_n_31]
set_property MARK_DEBUG true [get_nets top_inst/SPI_WRAPPER_inst_n_33]
set_property MARK_DEBUG true [get_nets top_inst/SPI_WRAPPER_inst_n_34]
set_property MARK_DEBUG true [get_nets top_inst/SPI_WRAPPER_inst_n_35]
set_property MARK_DEBUG true [get_nets top_inst/SPI_WRAPPER_inst_n_36]
set_property MARK_DEBUG true [get_nets top_inst/SPI_WRAPPER_inst_n_37]
set_property MARK_DEBUG true [get_nets top_inst/SPI_WRAPPER_inst_n_38]
connect_debug_port u_ila_0/probe11 [get_nets [list top_inst/p_0_in]]
connect_debug_port u_ila_0/probe13 [get_nets [list top_inst/SPI_WRAPPER_inst_n_31]]
connect_debug_port u_ila_0/probe14 [get_nets [list top_inst/SPI_WRAPPER_inst_n_32]]
connect_debug_port u_ila_0/probe15 [get_nets [list top_inst/SPI_WRAPPER_inst_n_33]]
connect_debug_port u_ila_0/probe16 [get_nets [list top_inst/SPI_WRAPPER_inst_n_34]]
connect_debug_port u_ila_0/probe17 [get_nets [list top_inst/SPI_WRAPPER_inst_n_35]]
connect_debug_port u_ila_0/probe18 [get_nets [list top_inst/SPI_WRAPPER_inst_n_36]]
connect_debug_port u_ila_0/probe19 [get_nets [list top_inst/SPI_WRAPPER_inst_n_37]]
connect_debug_port u_ila_0/probe20 [get_nets [list top_inst/SPI_WRAPPER_inst_n_38]]
connect_debug_port u_ila_0/probe24 [get_nets [list top_inst/uart_flipflops]]
connect_debug_port u_ila_0/probe25 [get_nets [list top_inst/UART_TRANSACTION_HANDLER_inst_n_6]]
connect_debug_port u_ila_0/probe26 [get_nets [list top_inst/UART_TRANSACTION_HANDLER_inst_n_11]]
connect_debug_port u_ila_0/probe27 [get_nets [list top_inst/UART_TRANSACTION_HANDLER_inst_n_12]]

set_property MARK_DEBUG true [get_nets top_inst/ADC_Ready2]
set_property MARK_DEBUG true [get_nets top_inst/ADC_Ready3]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH1[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH1[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH1[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH1[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH1[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH1[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH1[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH1[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH1[8]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH1[9]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH2[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH2[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH2[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH2[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH2[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH2[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH2[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH2[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH2[8]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH2[9]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH3[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH3[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH3[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH3[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH3[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH3[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH3[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH3[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH3[8]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH3[9]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH4[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH4[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH4[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH4[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH4[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH4[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH4[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH4[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH4[8]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_CH4[9]}]
connect_debug_port u_ila_0/probe0 [get_nets [list {top_inst/bartlett_CH4[0]} {top_inst/bartlett_CH4[1]} {top_inst/bartlett_CH4[2]} {top_inst/bartlett_CH4[3]} {top_inst/bartlett_CH4[4]} {top_inst/bartlett_CH4[5]} {top_inst/bartlett_CH4[6]} {top_inst/bartlett_CH4[7]} {top_inst/bartlett_CH4[8]} {top_inst/bartlett_CH4[9]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {top_inst/bartlett_CH1[0]} {top_inst/bartlett_CH1[1]} {top_inst/bartlett_CH1[2]} {top_inst/bartlett_CH1[3]} {top_inst/bartlett_CH1[4]} {top_inst/bartlett_CH1[5]} {top_inst/bartlett_CH1[6]} {top_inst/bartlett_CH1[7]} {top_inst/bartlett_CH1[8]} {top_inst/bartlett_CH1[9]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {top_inst/bartlett_CH2[0]} {top_inst/bartlett_CH2[1]} {top_inst/bartlett_CH2[2]} {top_inst/bartlett_CH2[3]} {top_inst/bartlett_CH2[4]} {top_inst/bartlett_CH2[5]} {top_inst/bartlett_CH2[6]} {top_inst/bartlett_CH2[7]} {top_inst/bartlett_CH2[8]} {top_inst/bartlett_CH2[9]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {top_inst/bartlett_CH3[0]} {top_inst/bartlett_CH3[1]} {top_inst/bartlett_CH3[2]} {top_inst/bartlett_CH3[3]} {top_inst/bartlett_CH3[4]} {top_inst/bartlett_CH3[5]} {top_inst/bartlett_CH3[6]} {top_inst/bartlett_CH3[7]} {top_inst/bartlett_CH3[8]} {top_inst/bartlett_CH3[9]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list top_inst/ADC_Ready2]]
connect_debug_port u_ila_0/probe9 [get_nets [list top_inst/ADC_Ready3]]


set_property MARK_DEBUG false [get_nets {top_inst/ADC_data2[9]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data1[6]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data1[2]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data1[0]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data2[7]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data3[3]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data3[4]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data3[1]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data3[2]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data3[0]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data2[8]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data2[1]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data2[2]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data1[1]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data1[3]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data1[4]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data1[5]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data1[7]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data1[8]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data1[9]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data2[0]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data2[5]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data2[6]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data2[3]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data2[4]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data3[7]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data3[9]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data3[5]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data3[6]}]
set_property MARK_DEBUG false [get_nets {top_inst/ADC_data3[8]}]
set_property MARK_DEBUG false [get_nets top_inst/ADC_Ready1]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_8]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_6]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_7]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_47]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_48]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_39]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_40]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_41]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_42]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_43]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_44]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_45]
set_property MARK_DEBUG false [get_nets top_inst/SPI_WRAPPER_inst_n_46]
set_property MARK_DEBUG false [get_nets top_inst/UART_TRANSACTION_HANDLER_inst_n_6]
set_property MARK_DEBUG false [get_nets top_inst/UART_TRANSACTION_HANDLER_inst_n_11]
set_property MARK_DEBUG false [get_nets top_inst/UART_TRANSACTION_HANDLER_inst_n_12]
set_property MARK_DEBUG false [get_nets top_inst/uart_flipflops]
set_property PACKAGE_PIN B18 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/SIPO0_in[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/SIPO0_in[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/SIPO0_in[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/SIPO0_in[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/SIPO0_in[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/SIPO0_in[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/SIPO0_in[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/SIPO0_in[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/p_0_in[8]}]


set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/op[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/op[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[11]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[19]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[21]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[24]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[29]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[30]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[31]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[8]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[14]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[17]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[20]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[22]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[25]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[10]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[12]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[13]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[15]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[16]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[28]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[9]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[18]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[23]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[26]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_dina[27]}]
set_property MARK_DEBUG true [get_nets top_inst/bram_ena]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[9]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[11]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[12]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[8]}]
set_property MARK_DEBUG true [get_nets {top_inst/bram_addra[10]}]

set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/Word_To_Send[7]}]
set_property MARK_DEBUG true [get_nets top_inst/Word_To_Send_en]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[20]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[23]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[26]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[28]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[30]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[10]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[14]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[16]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[21]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[25]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[9]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[18]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[19]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[22]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[24]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[27]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[31]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[11]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[8]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[12]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[13]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[15]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[17]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_datain[29]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_addr[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_addr[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_addr[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_addr[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_addr[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/reg_map_addr[5]}]
set_property MARK_DEBUG true [get_nets top_inst/uart_wen]
set_property MARK_DEBUG false [get_nets {top_inst/rx_data[0]}]
set_property MARK_DEBUG false [get_nets {top_inst/rx_data[1]}]
set_property MARK_DEBUG false [get_nets {top_inst/rx_data[2]}]
set_property MARK_DEBUG false [get_nets {top_inst/rx_data[3]}]
set_property MARK_DEBUG false [get_nets {top_inst/rx_data[4]}]
set_property MARK_DEBUG false [get_nets {top_inst/rx_data[5]}]
set_property MARK_DEBUG false [get_nets {top_inst/rx_data[6]}]
set_property MARK_DEBUG false [get_nets {top_inst/rx_data[7]}]
set_property MARK_DEBUG false [get_nets top_inst/rx_ready]

set_property MARK_DEBUG true [get_nets {top_inst/UART_inst/RX_Data_out[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_inst/RX_Data_out[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_inst/RX_Data_out[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_inst/RX_Data_out[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_inst/RX_Data_out[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_inst/RX_Data_out[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_inst/RX_Data_out[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_inst/RX_Data_out[7]}]
set_property MARK_DEBUG true [get_nets top_inst/UART_inst/RX_Data_Ready]

set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[8]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[14]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[24]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[29]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[30]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[39]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[35]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[37]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[36]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[18]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[9]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[17]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[19]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[23]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[33]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[28]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[34]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[31]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[32]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[10]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[12]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[21]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[22]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[26]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[27]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[38]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[13]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[11]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[15]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[16]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[20]}]
set_property MARK_DEBUG true [get_nets {top_inst/bartlett_inst/s_axis_data_tdata[25]}]
set_property MARK_DEBUG true [get_nets top_inst/bartlett_inst/dest_req]


set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[9]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[14]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[19]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[21]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[5]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[10]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[11]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[16]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[25]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[27]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[29]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[6]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[13]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[15]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[20]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[28]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[22]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[7]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[8]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[12]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[17]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[18]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[23]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[24]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[26]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[30]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_data_in[31]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/byte_counter[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/byte_counter[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/byte_counter[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/byte_counter[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_addr[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_addr[1]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_addr[2]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_addr[3]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_addr[4]}]
set_property MARK_DEBUG true [get_nets {top_inst/UART_TRANSACTION_HANDLER_inst/uart_addr[5]}]

set_property MARK_DEBUG true [get_nets {top_inst/btn_IBUF[0]}]
set_property MARK_DEBUG true [get_nets {top_inst/btn_IBUF[1]}]
connect_debug_port u_ila_0/probe5 [get_nets [list top_inst/bartlett_inst/dest_req]]
connect_debug_port u_ila_0/probe6 [get_nets [list top_inst/SPI_WRAPPER_inst_n_31]]
connect_debug_port u_ila_0/probe7 [get_nets [list top_inst/SPI_WRAPPER_inst_n_32]]
connect_debug_port u_ila_0/probe8 [get_nets [list top_inst/SPI_WRAPPER_inst_n_33]]
connect_debug_port u_ila_0/probe9 [get_nets [list top_inst/SPI_WRAPPER_inst_n_34]]
connect_debug_port u_ila_0/probe10 [get_nets [list top_inst/SPI_WRAPPER_inst_n_35]]
connect_debug_port u_ila_0/probe11 [get_nets [list top_inst/SPI_WRAPPER_inst_n_36]]


