#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Aug 30 13:35:47 EDT 2025
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim hilbert_tb_behav -key {Behavioral:sim_1:Functional:hilbert_tb} -tclbatch hilbert_tb.tcl -view /home/bigpi/AMD/Vivado/2022.2/Projects/hilbert_final/hilbert_tb_behav.wcfg -log simulate.log"
xsim hilbert_tb_behav -key {Behavioral:sim_1:Functional:hilbert_tb} -tclbatch hilbert_tb.tcl -view /home/bigpi/AMD/Vivado/2022.2/Projects/hilbert_final/hilbert_tb_behav.wcfg -log simulate.log

